### ISSUE TITLE
DataTable refactor/rewrite

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1043]
## Description

Old table is bad. We're rewriting it. See context (below) or https://github.com/sussol/react-native-data-table/issues/46 

## Plan

We'll operate a local import of code for the data table. At the end we'll take the core parts back to react-native-data-table repo

## Branches

**Feature branch:** #1043-data-table-rewrite

## Tasks
**Each task to have its own issue, branch and PR.**
### Utility
- [x] Styles
    - [x] New Props
        - ISSUE: #1119  
        - PR: #1120 
    - [x] Styles
        - ISSUE: #1090 
        - PR:   #1121 
    - [x] Row onPress
        - ISSUE: #1145 
        - PR:   #1146 
    - [x] Optimized virtualized list props
        - ISSUE: #1140 
        - PR:   #1150 
    - [x] Factoring renderCells
        - ISSUE: #1159 
        - PR: #1163 
    - [x] Factoring renderModal
        - ISSUE: #1160  
        - PR:  #1168 
    - [x] New ExpiryInputCell
        - ISSUE: #1155   
        - PR:  #1161 
    - [x] Replacing SearchBar component
        - ISSUE: #1176 
        - PR: #1178 
    - [x] Handle finalizing records not updating state
        - ISSUE: #1171 
        - PR: #1174 
    - [x] Handle navigation side effects not updating state
        - ISSUE: #1172 
        - PR: #1175 
    - [x] Programmatically scrolling data table.
        - ISSUE: #1181 
        - PR: #1187 
    - [x] Tidy up flux methods
        - ISSUE:  #1169 
        - PR: #1204 
    - [x] Dynamic actions 
        - ISSUE:  #1210
        - PR: #1213 
    - [x] Column update
        - ISSUE:  #1209 
        - PR: #1214 
    - [x] small updates
        - ISSUE:  #1252
        - PR:
    - [x] Column typing
        - ISSUE:  #1250
        - PR: #1250
    - [ ] State Initialisers
        - ISSUE:  #1249 
        - PR:
    - [x] Price and unit columns
        - ISSUE:  #1248 
        - PR: #1248 
    - [x] useCallback calls
        - ISSUE:  #1247 
        - PR: #1247 
    - [x] useSyncListener
        - ISSUE:  #1246 
        - PR: #1246 
        
### Pages
Need to rewrite all pages to use new data table.

- [x] CustomerInvoicePage for reference on all following pages 
    - [x] Basic component 
        - ISSUE: #1090
        - PR: #1108
    - [x] Sorting feature
        - ISSUE:  #1110
        - PR: #1114 
    - [x] Filtering feature
        - ISSUE: #1111
        - PR: #1115
    - [x] data-type synchronization **finish later #1123 blocker**
        - ISSUE: #1112
        - PR:  #1116 
    - [x] Refactor#1
        - ISSUE: #1113 
        - PR: #1117
    - [x] Refactor#2
        - ISSUE: #1137
        - PR: #1143 
    - [x] Tidy up
        - ISSUE: #1148 
        - PR: #1148
    - [x] TidyUp2
        - ISSUE: #1218 
        - PR: #1224 
- [x] CustomerInvoicesPage
    - ISSUE: #1125 
    - PR: #1164 
    - FOLLOW UP ISSUE: #1220
    - FOLLOW UP PR: #1223
- [x] CustomerRequisitionPage
    - ISSUE: #1126 
    - PR: #1227 
- [x] CustomerRequisitionsPage
    - ISSUE: #1127 
    - PR: #1226 
- [x] StockPage
    - ISSUE: #1128 
    - PR: #1257
- [x] StocktakeEditPage
    - ISSUE: #1129 
    - PR: #1192
    - ISSUE2: #1186 
    - PR2: #1193 
    -  ISSUE3: #1201
    -  PR3:  #1217 
    -  ISSUE4: #1199 
    -  PR4: #1221 
- [x] StocktakeManagePage
    - ISSUE: #1130 
    - PR: #1191 
    - ISSUE2: #1198 
    - PR2: #1216 
- [x] StocktakesPage
    - ISSUE: #1131 
    - PR: #1190 
    - ISSUE2:  #1197 
    - PR2: #1216 
- [x] SupplierInvoicePage
    - ISSUE: #1132 
    - PR: #1177 
    - ISSUE2: #1219  
    - PR2: #1222
- [x] SupplierInvoicesPage
    - ISSUE: #1133 
    - PR: #1225 
- [x] SupplierRequistionsPage
    - ISSUE: #1135 
    - PR: #1188 
    - ISSUE2: #1195 
    - PR: #1189 
- [x] SupplierRequisitionPage
    - ISSUE: #1134 
    - PR: #1189 
    - ISSUE2: #1196 
    - PR2: #1208 
- [x] Stocktake batch modal
    - ISSUE: #1138  
    - PR: #1229 
- [x] Regimen Modal
    - ISSUE: #1228 
    - PR: #1230 

### Post refactor

- [ ] Move data table code to react-native-data-table and publish
    - ISSUE: https://github.com/sussol/react-native-data-table/issues/47
    - PR: 
- [ ] Use npm package in mobile rather than local
    - ISSUE:  #1137
    - PR: https://github.com/sussol/react-native-data-table/pulls
- [x] Remove old unused code
    - ISSUE: #1165 
    - PR:
- [x] Merge to develop
    - ISSUE: #1043 
    - PR: #1355 
- [x] Testing
    - ISSUE: https://github.com/openmsupply/mobile/issues/1231

### Additional existing issues 
**These issues should either be fixed or closed with the new data table implementation**
- #992 
- #792
- #745 
- #742 
- #722 
- #683 
- #674 
- #651 
- #650 
- #621 
- #603 
- #437 
- #517 
- #379 
- #236 
- #77 
- #218
- #1036  

### Context
Old data table was slow, using deprecated ListView, A specific Realmjs version of the deprecated ListView component. Generic table page has significant problems with multiple unnecessary full re-renders.

## Design discussion
Addition context here https://github.com/sussol/react-native-data-table/issues/46
If necessary, discuss GenericPage/GenericTablePage design. Going to have a crack at CustomerInvoicePage to get a solid grasp of the challenges.

**Comment by Chris-Petty** [comment]
Would be better here IMO https://github.com/sussol/react-native-data-table/issues

Right questions though:

> * **Are we keeping realm? Or, if we can't decide this, are we writing this new data table in such a way that is completely decoupled from realm?** (I think coupling the data table with realm, if we are using it, offers quite a few benefits)

Decoupled. It's annoying for people wanting to use the table with anything other than realm. The coupling is Realm.ListView, but we're throwing that out with the rewrite anyway.

> * **Are we going to keep the data table as a separate NPM package?** I don't like having the table abstracted away, personally, but I can also see the benefit

I think executed well, it's a pretty sensible package to exist in it's own right. I'm not against getting generic table page into mobile, though. 2 levels out is exponentially more of a pain in the ass than 1 level.

> * **Are we using hooks?** (This will require upgrading react-native, which should probably happen regardless, but will have to happen sooner rather than later. Keeping in mind the vaccine module branch is already a version behind)

I say yes, though we're trading off backwards compatibility with older RN apps, with modern react APIs/style. Not that they are planning to deprecate the class API. 

> * **FlatList/VirtualizedList/Something else?** - FlatList is reall easy to use, whereas virtualized list offers more flexibility. I think FlatList would probably be sufficient.

I think FlatList would probably be sufficient, but I appreciate the flexibility of not being locked to down to Arrays.

> * **What 'extra's' are needed?** Expansions, sections?, custom components as cells, sorting, "switching" (i.e, click a 'menu' button on a row to offer different options), highlighting rows - I think at least thinking about this is a good idea as it can change a lot about how the table is written.

"Yes"

> * **Performance metrics** I think having baselines for rendering performance might be a good idea to have in place at the start, although this could be premature

Yes

> * **Tests** I think having jest upgraded and able to run tests would be extremely valuable

Yes

> * **refreshData** I think the use of refreshData is basically the biggest flaw in the current implementation and that it should not be used at all :)

Yes

**Live examples** Written in Expo or RN. Should flex the whole API. Might tie into automated tests.

**Comment by Chris-Petty** [comment]
> To be able to use the data table with 5,000 lines as effeciently and performant as with 1 line.

That's a pretty optimistic bar, but here's hoping there aren't hurdles haha.

**Comment by craigdrown** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactoring data table for mobile](https://trello.com/c/q8BzjUAI/114-refactoring-data-table-for-mobile)

**Comment by Chris-Petty** [comment]
Reopening this issue as epic

**Comment by joshxg** [comment]
Should most likely also do the realm explorer page.

Was thinking, there is the possibility to merge the feature after just a few main pages. Would be less of a burden on the merge/testing and also give opportunity to start developing on new features (IC P2) if the entire refactor isn't complete.

**Comment by joshxg** [comment]
# TESTING

## Customer Invoices Page
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ] 
## Customer Invoice Page
## Supplier Invoice Page
## Supplier Invoices Page
## Customer Requisitions Page
## Customer Requisition Page
## Supplier Requisitions Page
## Supplier Requisition Page
## Stocktakes Page
## Manage Stocktake Page
## Stocktake Edit Page
## Stock page

**Comment by joshxg** [comment]
@andreievg @Chris-Petty 

Questions regarding current implementation:

- Why does `RequisitionItem` have both`ourStockOnHand` (A getter) and also `stockOnHand` the field detailed above?

```
get ourStockOnHand() {
    const totalQuantity = this.item ? this.item.totalQuantity : null;
    const availableQuantity = this.linkedTransactionItem
      ? this.linkedTransactionItem.availableQuantity
      : null;

    return availableQuantity || totalQuantity;
  }
```
`RequisitionItem.stockOnHand` is essentially a snapshot - it is a field where the value is set on creation. If stock adjustments are made after creation, the field isn't updated? Is this intended behaviour? Is there a reason for both? sync?

- Also why is this not the sum of all batches for an items `totalQuantity`? Why when a requisition is a response, is the linked transactions items total quantity used?

**Comment by andreievg** [comment]
> @andreievg @Chris-Petty
> 
> Questions regarding current implementation:
> 
> * Why does `RequisitionItem` have both`ourStockOnHand` (A getter, below) and also `stockOnHand` a field on the object (only ever set on creation)?
> 
> ```
> get ourStockOnHand() {
>     const totalQuantity = this.item ? this.item.totalQuantity : null;
>     const availableQuantity = this.linkedTransactionItem
>       ? this.linkedTransactionItem.availableQuantity
>       : null;
> 
>     return availableQuantity || totalQuantity;
>   }
> ```
> 
> `RequisitionItem.stockOnHand` is essentially a snapshot - it is a field where the value is set on creation. If stock adjustments are made after creation, the field isn't updated? Is this intended behaviour? Is there a reason for both? sync?
> 

Yep, that's the intended behaviour, why ? Well first, for historic reasons (don't want old requisitions showing current stock on hand), also stock on hand affects suggested quantity, so don't want that changing.

> * Also why is this not the sum of all batches for an items `totalQuantity`? Why when a requisition is a response, is the linked transactions items total quantity used?

When user fulfils response requisitions, they can only supply the available quantity (difference between available and total ? -> unfinilised customer invoices reserver available stock, when they are finalised stock movement applies to total quantity)

**Comment by joshxg** [comment]
Closed by #1355

**Comment by joshxg** [comment]
Just need to port code to `react-native-data-table` repo, publish a new version, use that new version in mobile and remove the then-unused data table code

**Comment by wlthomson** [comment]
In terms of testing, this can be moved to DONE as soon as the remaining issues are tested.

**Comment by katherine-sussol** [comment]
Closing - looks more or less done (and if there was any testing missing, I think it's been in production long enough 😆 )? Any outstanding issues can be logged as a separate issue...
