### ISSUE TITLE
Mobile dashboard interface

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#1705]
## Description

@andreievg @mark-prins @diegoevangelisti @sworup @Chris-Petty 

Continuation/rewrite of the Mobile dashboard interface started in 2018.

### Context

Ivory Coast require reporting in mobile. Other countries are interested in mobile having a dashboard in mobile. Win win!

## Resources

- Feature Branch: https://github.com/openmsupply/mobile/tree/feature/dashboard
- Project board: https://github.com/openmsupply/mobile/projects/8?add_cards_query=is%3Aopen
- Related desktop issue: https://github.com/sussol/msupply/issues/2179
- ZIP of GIF/Pics of the current/old mobile dashboard: [MobileDashboard.zip](https://github.com/openmsupply/mobile/files/3970388/MobileDashboard.zip)
- Related wiki documentation:  [here](https://sussol.net/wiki/doku.php/msupply:design:web:dashboard?s%5B%5D=dashboard) and [here](https://docs.msupply.org.nz/preferences:dashboard)

### Interface
- The interface for the dashboard was written a year ago https://github.com/openmsupply/mobile/issues/441.
- Just going to go with this interface, mainly due to time constraints. Can iterate and polish as we move forward.
- This branch is very old and not in a mergeable state. The best way forward is to create a new branch, reusing code where possible. 
- This uses [`VictoryCharts`](https://formidable.com/open-source/victory/docs/victory-chart/) 
- Old branch here: https://github.com/openmsupply/mobile/tree/%23441-dashboard

![MobileDashboard-2019-12-05 at 4 44 45 PM](https://user-images.githubusercontent.com/35858975/70941082-92f3b700-20b0-11ea-9004-b5c81aeff872.png)

### Backend

- The reports are generated on the primary which are reports from the "old" dashboard [here](https://sussol.net/wiki/doku.php/msupply:design:web:dashboard?s%5B%5D=dashboard) and [here](https://docs.msupply.org.nz/preferences:dashboard)
- The discussion on the desktop backend is [here](https://github.com/sussol/msupply/issues/2179)

#### Mobile side

- Mobile will be receiving reports via JSON which are precalculated.
- Mobile will store these records as a `Report` record.

![image](https://user-images.githubusercontent.com/35858975/70942284-334adb00-20b3-11ea-8430-a59546b4b920.png)

- Where `data` is the report stringified JSON for a report

### Implementation

- [x] Add dependecies, victory chart etc
    - ISSUE: https://github.com/openmsupply/mobile/issues/1706
    - PR: #1717 
- [x] Add demo data
    - ISSUE: https://github.com/openmsupply/mobile/issues/1707
    - PR: #1753 
- [x] Add `Report` class to realm schema
    - ISSUE: https://github.com/openmsupply/mobile/issues/1708
    - PR: #1722
- [x] Add `Report` getters and setters
    - ISSUE: https://github.com/openmsupply/mobile/issues/1709
    - PR: #1723
- [x] Add `Report` to `incomingSyncUtils`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1710
    - PR: #1725
- [ ] Add dashboard Localization
    - ISSUE: https://github.com/openmsupply/mobile/issues/1711
    - PR: #1865 
- [x] Add `Dashboard` button to `MenuPage`
    - ISSUE: https://github.com/openmsupply/mobile/issues/1712
    - PR: #1731
- [x] Add `PieChart` component
    - ISSUE: https://github.com/openmsupply/mobile/issues/1713
    - PR: #1740 
- [x] Add `LineChart` component
    - ISSUE: #1742 
    - PR: #1747 
- [x] Add `BarChart` component
    - ISSUE: #1741 
    - PR: #1752
- [x] Add `ReportRow` component
    - ISSUE: #1754
    - PR: #1757 
- [x] Add `ReportCell` component
    - ISSUE: #1755
    - PR: #1756 
- [x] Add `ReportTable` component
    - ISSUE: #1744
    - PR: #1758
- [x] Add `ReportChart` component
    - ISSUE: #1713 
    - PR: #1760 
- [x] Add `ReportSideBar` component
    - ISSUE: https://github.com/openmsupply/mobile/issues/1714
    - PR: #1763 
- [x] Add `DashboardPage` component
    - ISSUE: https://github.com/openmsupply/mobile/issues/1716
    - PR: #1764 
- [x] Add `Dashboard` Reducer
    - ISSUE: https://github.com/openmsupply/mobile/issues/1715
    - PR: #1819 
- [x] Placeholder screen when no dashboard reports 
    - ISSUE: #1847 
    - PR: 
- [ ] Add docs string for all files added in feature/Dashboard
    - ISSUE: #1745 
    - PR:

**Comment by diegoevangelisti** [comment]
Great job @joshxg, thank for that. I will start working on this right now, issues from top to bottom.

**Comment by andreievg** [comment]
@diegoevangelisti, this is the widget that was used in vaccine module, might get some inspiration from it: https://github.com/openmsupply/mobile/blob/vaccine-development/src/widgets/VaccineChart.js

**Comment by diegoevangelisti** [comment]
> @diegoevangelisti, this is the widget that was used in vaccine module, might get some inspiration from it: https://github.com/openmsupply/mobile/blob/vaccine-development/src/widgets/VaccineChart.js

Thanks, pretty useful indeed!

**Comment by joshxg** [comment]
Thanks @diegoevangelisti 

#1924 is merged.

Going to keep this open as we do still need:

1) Test cases
2) Documentation (See desktop draft docs here: https://docs.msupply.org.nz/playground:2020-01_sworup_dashboard )
3) Remove the test data file

**Comment by diegoevangelisti** [comment]
This is all good news. Thanks to you @joshxg!

**Comment by joshxg** [comment]
Fantastic! Thanks @diegoevangelisti this has been merged and released
