### ISSUE TITLE
TESTING: Prescription Page

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2108]
# TESTING

This is an issue for testing `PrescriptionPage`

# PrescriptionPage

## General
- [ ] When navigating initially to the prescription page, you land on the "Select Prescriber" page
- [ ] Title (top left) is "Prescription XXX" Where XXX is the invoice number
- [ ] There is a 3 progress steps at the top: `"Select the prescriber"`, `"Select Items"` and `"Finalise"`
- [ ] There is a patient text field, below which is the patient name. 
- [ ] When a step is completed, you can navigate back to that step, but you can never navigate past a step without completing the current step.

## Patient label

- [ ] Patient first and last name is displayed and is correct.
- [ ] History icon is displayed:
  - [ ] History icon is pressable: see dispensing tests for patient modal for details (#2106).
- [ ] Edit icon is displayed:
   - [ ] If patient is local, edit icon is a "pencil".
   - [ ] If patient is non-local, edit icon is a "book".
   - [ ] Edit icon is pressable: see dispensing tests for patient modal for details (#2106).

## Prescriber label

- [ ] ONLY displays after selecting a prescriber
- [ ] The prescriber first and last name is correct
- [ ] Edit icon is displayed:
  - [ ] If prescriber is local, edit icon is a "pencil"
  - [ ] If prescriber is non-local, edit icon is a "book"
  - Edit icon is pressable:  see dispensing tests for prescriber modal for details (#2106).

## Select the prescriber

- [ ] Lists all prescribers, including non-local prescribers.

### Columns

- [ ] FIRST NAME
    - [ ] Sortable 
    - [ ] Not-editable
    - [ ] Not-Clickable
    - [ ] Displays the correct prescriber first name
- [ ] LAST NAME
    - [ ] Sortable 
    - [ ] Not-editable
    - [ ] Not-Clickable
    - [ ] Displays the correct prescriber last name
- [ ] SELECT
    - [ ] Not-sortable
    - [ ] Not-editable
    - [ ] Clickable
    - [ ] Pressing selects this prescriber

### Buttons

- [ ] New prescriber button is displayed:
  - [ ] Pressing opens the add prescriber modal: see dispensing tests for prescriber modal for details (#2106).

### Search bar

- [ ] Filters by last name.
- [ ] If a comma is used, the input immediately after the comma filters by first name.
- [ ] If a comma is used, the input immediately the first name can be used to filter by certain keys (currently only date of birth, which is `-d`). E.g. `"g, j -d 1980"` filters by first name starting with `"j"`, last name `"g"`, and date of birth from `1980`.

### Item list

- [ ] Lists all items visible in this store.
- [ ] Items are sorted alphabetically and by quantity: e.g. all items with a non-zero quantity appear first and are sorted alphabetically, followed by all items with no quantity.
- [ ] Pressing a row adds it to the shopping cart.
- [ ] The `"Next"` button is only enabled once there is AT LEAST one item with a quantity of at least `1` in the prescription.

### Columns

- [ ] Code
    - [ ] Not-Sortable 
    - [ ] Not-editable
    - [ ] Displays the correct code for the item
- [ ] Name
    - [ ] Not-Sortable 
    - [ ] Not-editable
    - [ ] Displays the correct name for the item
- [ ] Quantity
    - [ ] Not-sortable
    - [ ] Not-editable
    - [ ] Displays the correct available quantity for the item

## Cart

- [ ] Lists all items which are in this prescription
- [ ] Each row displays the name and code of the item.
- [ ] Quantity being ordered is displayed with a + and - button on left and right
- [ ] + and -  buttons increment the amount
- [ ] Holding the + and - buttons continually increment the amount, slowly increasing in speed
- [ ] Quantity cannot exceed the amount available
- [ ] Quantity cannot go below 0
- [ ] Delete button removes this row from the cart
- [ ] Text input for direction has placeholder "Usage Direction"
- [ ] Able to enter text into the text input
- [ ] Inputting any abbreviation auto-inserts the expansion of that abbreviation
- [ ] Drop down menu displays all default directions for this item
- [ ] If payments are enabled, price is also displayed alongside the code
- [ ] Adding multiple items enables scrolling in the cart
- [ ] When scrolling is enabled, clicking on a text input field correctly scrolls the input such that the input is not obstructed by the keyboard

## Summary (with payments disabled)

- [ ] Displays each item which was ordered
- [ ] Shows the item name, code and directions which were entered
- [ ] Shows the quantity which was ordered
- [ ] If payments are enabled then the `"Complete"` button is only enabled when the payment is VALID, i.e. fully paid for.

## Summary (with payments enabled)

- [ ] Displays a `"Payment"` summary on the right hand side in addition to the above summary
- [ ] Has a drop down which displays the payment type:
    - [ ] Drop down displays all available payment types
    - [ ] Selecting a payment type correctly switches the payment type
    - [ ] Selecting a payment type correctly applies that payment type to the prescription transaction
    - [ ] Selecting a payment type correctly applies that payment type to the receipt transaction
- [ ] Payment amount
    - [ ] Both inputs can be focussed and edited
    - [ ] When either input is submitted, the other is focussed
    - [ ] First input is the dollar amount
    - [ ] Second input is the cent amount
    - [ ] Entering a payment amount correctly adjusts other values:
      - [ ] `"Credit used"` is set to the subtotal minus the amount covered by payment and insurance
      - [ ] `"Change required"` is the amount paid which exceeds the prescription total
- [ ] Available credit
    - [ ] Displays the total available credit for a patient
- [ ] Credit Used
    - [ ] Displays the credit being used for this prescription
    - [ ] Correctly updates when other details are changed, e.g. payment or insurance amount
    - [ ] When there is not enough credit, an error message is displayed.
- [ ] Subtotal
    - [ ] Shows the amount of the prescription before insurance is considered (if insurance is enabled)
- [ ] Insurance discount rate (if insurance is enabled)
    - [ ] Shows the % discount provided by the currently selected insurance policy
- [ ] Insurance discount amount (if insurance is enabled)
    - [ ] Shows the amount of the prescription total covered by the selected insurance policy
- [ ] Change required
    - [ ] Shows when the payment amount and credit used is greater than the subtotal

## Summary (with transaction categories)

- [ ] When there is a prescription transaction category defined, there is a drop down selection.
- [ ] When there is no prescription transaction category defined, there is no drop down selection.
- [ ] Selecting a transaction category applies that category to the prescription

## Summary (with patient types)

- [ ] When the patient types are enabled, there is a drop down selection
- [ ] When the patient types are not enabled there is no drop down selection
- [ ] Selecting a payment type applies that patient type to the prescription (`prescription.user1`)

**Comment by diegoevangelisti** [comment]
# TESTING

This is an issue for testing `PrescriptionPage`

# PrescriptionPage

## General
- [x] When navigating initially to the prescription page, you land on the "Select Prescriber" page
- [x] Title (top left) is "Prescription XXX" Where XXX is the invoice number
- [x] There is a 3 progress steps at the top Select The prescriber, Select Items and Finalise
- [x] There is a Patient header, which shows the patients name and last name underneath
- [x] When a step is completed, you can navigate back to that step, but you can never navigate past a step without completing the current step.

## Patient label
- [x] The patient first and last name is correct
- [x] Two buttons:
    - [x] History: See dispensing edit/new modal
    - [x] Edit: See dispensing edit/new modal

## Prescriber label
- [x] ONLY displays after selecting a prescriber
- [x] The prescriber first and last name is correct
- [x] One button:
    - [x] Edit: See prescriber edit/new modal

## Select The prescriber
- [x] Lists all prescribers 
### Columns
- [x] First Name
    - [x] Sortable 
    - [x] Not-editable
    - [x] Not-Clickable
    - [x] Displays the correct First Name for the prescriber
- [x] Last Name
    - [x] Sortable 
    - [x] Not-editable
    - [x] Not-Clickable
    - [x] Displays the correct last name for the prescriber
- [x] SELECT
    - [x] Not-sortable
    - [x] Not-editable
    - [x] Clickable
    - [x] Pressing selects this prescriber
### Add Prescriber Button
- [x] Opens the Add Prescriber modal. See Dispensing: Add/edit Prescriber

### SearchBar
- [x] Filters by LAST NAME if a COMMA is used, anything AFTER is used to filter first name and keys -d for DOB: i.e. g, j -d 1980 filters by first name starting with j and last name g and date of birth FROM 1980

## Select Items

### Item List
- [x] Lists all items visible in this store.
- [x] Items are sorted alphabetically and by quantity: i.e. All items with quantity first sorted alphabetically, then all items with no quantity next.
- [x] Clicking on a row adds it to the shopping cart
- [x] The NEXT button is only enabled once there is AT LEAST one item, with one quantity in the prescription
### Columns
- [x] Code
    - [x] Not-Sortable 
    - [x] Not-editable
    - [x] Displays the correct code for the item
- [x] Name
    - [x] Not-Sortable 
    - [x] Not-editable
    - [x] Displays the correct name for the item
- [x] Quantity
    - [x] Not-sortable
    - [x] Not-editable
    - [x] Displays the correct available quantity for the item

## Cart
- [x] Lists all items which are in this prescription
- [x] Each row displays the name and code of the item.
- [x] Quantity being ordered is displayed with a + and - button on left and right
- [x] + and -  buttons increment the amount
**These + and - buttons are working but are too much sensitive (don't know how's going to be in a really tablet though), a simple short click is incrementing or decrementing the quantity by 2**
![buttonsitems1](https://user-images.githubusercontent.com/32987464/73797401-d0550500-4814-11ea-8ba6-476c7da75839.gif)

- [ ] Holding the + and - buttons continually increment the amount, slowly increasing in speed
**Related with the previous step, I _believe_ it's too fast :-)**

- [x] Quantity cannot exceed the amount available
- [x] Quantity cannot go below 0
- [x] Delete button removes this row from the cart
- [x] Text input for direction has placeholder "Usage Direction"
- [x] Able to enter text into the text input


- [x] Inputting any abbreviation auto-inserts the expansion of that abbreviation
- [ ] Drop down menu displays all default directions for this item
**Can't test this one**

- [ ] [WHEN USING PAYMENTS IS ENABLED:] Price is also displayed alongside the code
**Prices are being displayed but value is $0.00 even if there's a different selling price**
Example:
Selling price: $40.00
<img width="997" alt="Screen Shot 2020-02-05 at 1 14 52 PM" src="https://user-images.githubusercontent.com/32987464/73799019-89b5d980-4819-11ea-8761-8af650e13283.png">

Still showing $0.00 in the prescription:
![Screen Shot 2020-02-05 at 1 07 24 PM](https://user-images.githubusercontent.com/32987464/73798960-53785a00-4819-11ea-8dbf-4cbd855d00c3.png)

Apart from that, prices are being processed somehow because the price x quantity is calculated as expected (2 x $40 = $ 80 as shown in the picture below):
![Screen Shot 2020-02-05 at 2 15 07 PM](https://user-images.githubusercontent.com/32987464/73802240-ed440500-4821-11ea-8e2c-a84f9ad81516.png)

- [x] Adding multiple items enables scrolling in the cart
- [x] When scrolling is enabled, clicking on a textinput correctly scrolled the input such that the input is not obstructed by the keyboard

## Summary
- [x] Displays each item which was ordered
- [x] Shows the item name, code and directions which were entered
- [x] Shows the quantity which was ordered
- [x] If payments are enabled then the COMPLETE button is only enabled when the payment is VALID  i.e. fully paid for.

## Summary [With PAYMENTS enabled]
- [x] Displays a PAYMENT summary on the right hand side in addition to the above summary
- [ ] Has a drop down which displays the payment TYPE
    - [ ] Drop down displays all transactionPaymentType available: see Desktop/preferences/options/transactionPaymentType
**There's not a dropdown in my case, just what I show below (not different transaction payment types available I guess)**
![Screen Shot 2020-02-05 at 2 25 23 PM](https://user-images.githubusercontent.com/32987464/73802723-5d06bf80-4823-11ea-93bb-bbfb3346e135.png)

    - [ ] Selecting a payment type correctly switches the payment type
**Not allow to test, same as previous item**
- [ ] PAYMENT AMOUNT
    - [x] Entering a payment amount correctly adjusts other values:
    - [x] CreditUsed becomes the prescription sub total-insurance[if enabled]-payment amount
    - [x] change required is the amount exceeding the prescription total.
    - [x] Has two inputs. When submitting one, focus' the other.
    - [x] First input is the dollar amount
    - [x] Second input is the cent amount
- [x] Available credit
    - [x] Displays the total available credit for a patient
- [x] Credit Used
    - [x] Credit used is always updated and displays the credit being used for this prescription
    - [x] When there is not enough credit, an error message is displayed: saying there is not enough credit.
- [x] Subtotal
    - [x] Shows the amount of the prescription when insurance is not considered [if enabled]
- [x] Insurance discount rate [ IF INSURANCE ENABLED ]
    - [x] Shows the % discount the currently selected insurance policy provides
- [x] Insurance discount amount [ IF INSURANCE ENABLED ]
    - [x] Shows the amount of the prescription total the insurance is covering.
- [x] Change required
    - [x] Shows when the payment amount - credit used - subtotal is > 0 

## Summary [With Transaction Categories]
- [x] When there is a prescription
 Transaction category defined, there is a drop down selection.
- [x] When there isn't a prescription Transaction category defined, there is no drop down selection.
- [x] Selecting a Transaction Category applies that category to the prescription

**Leave this one by now because I'm not sure how to select different patient types**
## Summary [With Patient Types enabled: `usesPatientTypes`]
- [ ] When the patient types are enabled, there is a drop down selection
- [ ] When the patient types are not enabled there is no drop down selection
- [ ] Selecting a patient type applies that patient type to the prescription.user1 field

**Extra** (I didn't find a proper section where to add this one, sorry)

Something found related with insurance policies. Even after adding a couple of them, the drop down is not allowing me to select any option:

![Screen Shot 2020-02-05 at 3 29 29 PM](https://user-images.githubusercontent.com/32987464/73805743-69434a80-482c-11ea-84c2-ed356b3d5cf6.png)

**Comment by joshxg** [comment]
@diegoevangelisti 

Amazing thanks so much.

Have made issues here:

- https://github.com/openmsupply/mobile/issues/2149 
- https://github.com/openmsupply/mobile/issues/2151
- https://github.com/openmsupply/mobile/issues/2150

Regarding the email validation - at the moment on desktop there is no validation, so was just following the same behavior for now

**Comment by nmadruga** [comment]
Status: In progress
## Focus on syncing with mSupply Desktop!

# TESTING

This is an issue for testing `PrescriptionPage`

# PrescriptionPage

## General
- [ ] When navigating initially to the prescription page, you land on the "Select Prescriber" page
- [ ] Title (top left) is "Prescription XXX" Where XXX is the invoice number
- [ ] There is a 3 progress steps at the top Select The prescriber, Select Items and Finalise
- [ ] There is a Patient header, which shows the patients name underneath
- [ ] When a step is completed, you can navigate back to that step, but you can never navigate past a step without completing the current step.

## Patient label
- [ ] The patient first and last name is correct
- [ ] Two buttons:
    - [ ] History: See dispensing edit/new modal
    - [ ] Edit: See dispensing edit/new modal

## Prescriber label
- [ ] ONLY displays after selecting a prescriber
- [ ] The prescriber first and last name is correct
- [ ] One button:
    - [ ] Edit: See prescriber edit/new modal

## Select The prescriber
- [ ] Lists all prescribers 
### Columns
- [ ] First Name
    - [ ] Sortable 
    - [ ] Not-editable
    - [ ] Not-Clickable
    - [ ] Displays the correct First Name for the prescriber
- [ ] Last Name
    - [ ] Sortable 
    - [ ] Not-editable
    - [ ] Not-Clickable
    - [ ] Displays the correct last name for the prescriber
- [ ] SELECT
    - [ ] Not-sortable
    - [ ] Not-editable
    - [ ] Clickable
    - [ ] Pressing selects this prescriber
### Add Prescriber Button
- [ ] Opens the Add Prescriber modal. See Dispensing: Add/edit Prescriber

### SearchBar
- [ ] Filters by LAST NAME if a COMMA is used, anything AFTER is used to filter first name and keys -d for DOB: i.e. g, j -d 1980 filters by first name starting with j and last name g and date of birth FROM 1980



## Select Items

### Item List
- [ ] Lists all items visible in this store.
- [ ] Items are sorted alphabetically and by quantity: i.e. All items with quantity first sorted alphabetically, then all items with no quantity next.
- [ ] Clicking on a row adds it to the shopping cart
- [ ] The NEXT button is only enabled once there is AT LEAST one item, with one quantity in the prescription
### Columns
- [ ] Code
    - [ ] Not-Sortable 
    - [ ] Not-editable
    - [ ] Displays the correct code for the item
- [ ] Name
    - [ ] Not-Sortable 
    - [ ] Not-editable
    - [ ] Displays the correct name for the item
- [ ] Quantity
    - [ ] Not-sortable
    - [ ] Not-editable
    - [ ] Displays the correct available quantity for the item

## Cart
- [ ] Lists all items which are in this prescription
- [ ] Each row displays the name and code of the item.
- [ ] Quantity being ordered is displayed with a + and - button on left and right
- [ ] + and -  buttons increment the amount
- [ ] Holding the + and - buttons continually increment the amount, slowly increasing in speed
- [ ] Quantity cannot exceed the amount available
- [ ] Quantity cannot go below 0
- [ ] Delete button removes this row from the cart
- [ ] Text input for direction has placeholder "Usage Direction"
- [ ] Able to enter text into the text input
- [ ] Inputting any abbreviation auto-inserts the expansion of that abbreviation
- [ ] Drop down menu displays all default directions for this item
- [ ] [WHEN USING PAYMENTS IS ENABLED:] Price is also displayed alongside the code
- [ ] Adding multiple items enables scrolling in the cart
- [ ] When scrolling is enabled, clicking on a textinput correctly scrolled the input such that the input is not obstructed by the keyboard

## Summary
- [ ] Displays each item which was ordered
- [ ] Shows the item name, code and directions which were entered
- [ ] Shows the quantity which was ordered
- [ ] If payments are enabled then the COMPLETE button is only enabled when the payment is VALID  i.e. fully paid for.

## Summary [With PAYMENTS enabled]
- [ ] Displays a PAYMENT summary on the right hand side in addition to the above summary
- [ ] Has a drop down which displays the payment TYPE
    - [ ] Drop down displays all transactionPaymentType available: see Desktop/preferences/options/transactionPaymentType
    - [ ] Selecting a payment type correctly switches the payment type
- [ ] PAYMENT AMOUNT
    - [ ] Entering a payment amount correctly adjusts other values:
    - [ ] CreditUsed becomes the prescription sub total-insurance[if enabled]-payment amount
    - [ ] change required is the amount exceeding the prescription total.
    - [ ] Has two inputs. When submitting one, focus' the other.
    - [ ] First input is the dollar amount
    - [ ] Second input is the cent amount
- [ ] Available credit
    - [ ] Displays the total available credit for a patient
- [ ] Credit Used
    - [ ] Credit used is always updated and displays the credit being used for this prescription
    - [ ] When there is not enough credit, an error message is displayed: saying there is not enough credit.
- [ ] Subtotal
    - [ ] Shows the amount of the prescription when insurance is not considered [if enabled]
- [ ] Insurance discount rate [ IF INSURANCE ENABLED ]
    - [ ] Shows the % discount the currently selected insurance policy provides
- [ ] Insurance discount amount [ IF INSURANCE ENABLED ]
    - [ ] Shows the amount of the prescription total the insurance is covering.
- [ ] Change required
    - [ ] Shows when the payment amount - credit used - subtotal is > 0 

## Summary [With Transaction Categories]
- [ ] When there is a prescription Transaction category defined, there is a drop down selection.
- [ ] When there is a prescription Transaction category defined, there is no drop down selection.
- [ ] Selecting a Transaction Category applies that category to the prescription

## Summary [With Patient Types enabled: `usesPatientTypes`]
- [ ] When the patient types are enabled, there is a drop down selection
- [ ] When the patient types are not enabled there is no drop down selection
- [ ] Selecting a patient type applies that patient type to the prescription.user1 field

**Comment by nmadruga** [comment]
OK. My test is finished for today. I'll be waiting on the issues fixes to continue re-testing and do tests that were not reachable without the fixes tomorrow.

**Comment by joshxg** [comment]
@nmadruga I think all problems are in PR at the moment :)

**Comment by nmadruga** [comment]
Cool. Fixes are looking good. A have approved the PRs for the ones that were actually bugs and for the issue relating to prices #2285 it's more like a suggestion now than a big issue, so not a blocker. I just couldn't exactly find how to test those 2:

**Comment by wlthomson** [comment]
Closing as looks like this round of testing is completed. Please reopen if I've made a mistake!

**Comment by wlthomson** [comment]
`Updated for v5.0.0`.

**Comment by ArpitaSussol** [comment]
Tested in 5.0.0 rc3

# TEST

# PrescriptionPage

## General
- [x] When navigating initially to the prescription page, you land on the "Select Prescriber" page
- [x] Title (top left) is "Prescription XXX" Where XXX is the invoice number
- [x] There is a 3 progress steps at the top Select The prescriber, Select Items and Finalise
- [x] There is a Patient header, which shows the patients name underneath
- [x] When a step is completed, you can navigate back to that step, but you can never navigate past a step without completing the current step.

## Patient label
- [x] The patient first and last name is correct
- [x] Two buttons:
    - [x] History: See dispensing edit/new modal
    - [x] Edit: See dispensing edit/new modal

## Prescriber label
- [x] ONLY displays after selecting a prescriber
- [x] The prescriber first and last name is correct
- [x] One button:
    - [x] Edit: See prescriber edit/new modal

## Select The prescriber
- [x] Lists all prescribers 
### Columns
- [x] First Name
    - [x] Sortable 
    - [x] Not-editable
    - [x] Not-Clickable => If you clock anywhere it will select the Prescriber! OK
    - [x] Displays the correct First Name for the prescriber
- [x] Last Name
    - [x] Sortable 
    - [x] Not-editable
    - [x] Not-Clickable => If you clock anywhere it will select the Prescriber! OK
    - [x] Displays the correct last name for the prescriber
- [x] SELECT
    - [x] Not-sortable
    - [x] Not-editable
    - [x] Clickable => If you clock anywhere it will select the Prescriber! OK
    - [x] Pressing selects this prescriber
### Add Prescriber Button
- [x] Opens the Add Prescriber modal. See Dispensing: Add/edit Prescriber

**Comment by wlthomson** [comment]
@ArpitaSussol Thanks :tada:!

**Comment by wlthomson** [comment]
Priority for `v7` is WHO qualification, so these tests can be bumped to a later minor/major.

**Comment by ArpitaSussol** [comment]
### TESTING in V7.0.0 rc11


Tested in 5.0.0 rc3

# TEST

# PrescriptionPage

## General
- [x] When navigating initially to the prescription page, you land on the "Select Prescriber" page
- [x] Title (top left) is "Prescription XXX" Where XXX is the invoice number
- [x] There is a 3 progress steps at the top Select The prescriber, Select Items and Finalise
- [x] There is a Patient header, which shows the patients name underneath
- [x] When a step is completed, you can navigate back to that step, but you can never navigate past a step without completing the current step.

## Patient label
- [x] The patient first and last name is correct
- [x] Two buttons:
    - [x] History: See dispensing edit/new modal
    - [x] Edit: See dispensing edit/new modal

## Prescriber label
- [x] ONLY displays after selecting a prescriber
- [x] The prescriber first and last name is correct
- [x] One button:
    - [x] Edit: See prescriber edit/new modal

## Select The prescriber
- [x] Lists all prescribers 
### Columns
- [x] First Name
    - [x] Sortable 
    - [x] Not-editable
    - [x] Not-Clickable => If you clock anywhere it will select the Prescriber! OK
    - [x] Displays the correct First Name for the prescriber
- [x] Last Name
    - [x] Sortable 
    - [x] Not-editable
    - [x] Not-Clickable => If you clock anywhere it will select the Prescriber! OK
    - [x] Displays the correct last name for the prescriber
- [x] SELECT
    - [x] Not-sortable
    - [x] Not-editable
    - [x] Clickable => If you clock anywhere it will select the Prescriber! OK
    - [x] Pressing selects this prescriber
### Add Prescriber Button
- [x] Opens the Add Prescriber modal. See Dispensing: Add/edit Prescriber

### SearchBar
- [x] Filters by LAST NAME if a COMMA is used, anything AFTER is used to filter first name and keys -d for DOB: i.e. g, j -d 1980 filters by first name starting with j and last name g and date of birth FROM 1980



## Select Items

### Item List
- [x] Lists all items visible in this store.
- [x] Items are sorted alphabetically and by quantity: i.e. All items with quantity first sorted alphabetically, then all items with no quantity next.
- [x] Clicking on a row adds it to the shopping cart
- [x] The NEXT button is only enabled once there is AT LEAST one item, with one quantity in the prescription
### Columns
- [x] Code
    - [x] Not-Sortable 
    - [x] Not-editable
    - [x] Displays the correct code for the item
- [x] Name
    - [x] Not-Sortable 
    - [x] Not-editable
    - [x] Displays the correct name for the item
- [x] Quantity
    - [x] Not-sortable
    - [x] Not-editable
    - [x] Displays the correct available quantity for the item

## Cart
- [x] Lists all items which are in this prescription
- [x] Each row displays the name and code of the item.
- [x] Quantity being ordered is displayed with a + and - button on left and right
- [x] + and -  buttons increment the amount
- [x] Holding the + and - buttons continually increment the amount, slowly increasing in speed
- [x] Quantity cannot exceed the amount available
- [x] Quantity cannot go below 0
- [x] Delete button removes this row from the cart
- [x] Text input for direction has placeholder "Usage Direction"
- [x] Able to enter text into the text input
- [x] Inputting any abbreviation auto-inserts the expansion of that abbreviation
- [x] Drop down menu displays all default directions for this item
- [x] Adding multiple items enables scrolling in the cart
- [x] When scrolling is enabled, clicking on a textinput correctly scrolled the input such that the input is not obstructed by the keyboard

## Summary
- [x] Displays each item which was ordered
- [x] Shows the item name, code and directions which were entered
- [x] Shows the quantity which was ordered
- [x] COMPLETE button is always enabled



# TESTING with PAYMENTS enabled



## Summary
- [x] If payments are enabled then the COMPLETE button is only enabled when the payment is VALID  i.e. fully paid for.
- [x] Displays a PAYMENT summary on the right hand side in addition to the above summary
- [x] Has a drop down which displays the payment TYPE
    - [x] Drop down displays all transactionPaymentType available
    - [x] Selecting a payment type correctly switches the payment type
    - [x] The payment type start as 'Select a payment type' 
- [x] PAYMENT AMOUNT
    - [x] Entering a payment amount correctly adjusts other values:
    - [x] CreditUsed becomes the prescription sub total-insurance[if enabled]-payment amount
    - [x] change required is the amount exceeding the prescription total.
    - [x] Has two inputs. When submitting one, focus' the other.
    - [x] First input is the dollar amount
    - [x] Second input is the cent amount
- [ ] Available credit 
    - [ ] Displays the total available credit for a patient
- [ ] Credit Used
    - [ ] Credit used is always updated and displays the credit being used for this prescription
    - [ ] When there is not enough credit, an error message is displayed: saying there is not enough credit.
- [x] Subtotal
    - [x] Shows the amount of the prescription when insurance is not considered [if enabled]
- [x] Insurance discount rate [ IF INSURANCE ENABLED ]
    - [x] Shows the % discount the currently selected insurance policy provides
- [x] Insurance discount amount [ IF INSURANCE ENABLED ]
    - [x] Shows the amount of the prescription total the insurance is covering.
- [x] Change required
    - [x] Shows when the payment amount - credit used - subtotal is > 0 

# TESTING with Patient Types enabled [`usesPatientTypes`]
## Summary
- [x] When the patient types are enabled, there is a drop down selection 
- [x] When the patient types are not enabled there is no drop down selection
- [x] Selecting a patient type applies that patient type to the prescription.user1 field

# TESTING with Transaction Categories enabled
## Summary
- [x] When there is a prescription Transaction category defined, there is a drop down selection.
- [x] When there is a prescription Transaction category defined, there is no drop down selection.
- [x] Selecting a Transaction Category applies that category to the prescription
