### ISSUE TITLE
4.0.X Release Discussion

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2444]
Major release discussion: https://github.com/openmsupply/mobile/issues/1978
Minor Release discussion: #2445  

This issue is for discussions on issues with the 4.0.X release.

If you have found an issue which you think needs urgent attention, feel free to make a comment here.

You can also keep an eye on this issue to quickly be aware of any issues we find with the current release.

# Releases

### `4.0.1`
- [x] Incorrect insurance validation: #2433 
- [x] Stocktake row with no underlying item: #2448 
- [x] Prevent duplicate insurance policy numbers: #2460 
- [x] Patients not correctly saving: #2470 
- [x] Insurance not displaying after being synced: #2471 
- [x] Sync issues: #2473 
- [x] Stocktake program names not showing: #2490.
- [x] Incorrect patient credit calculation: #2496.

### `4.0.2`

- [x] Supplier requisition isVisible prop undefined: #2515
- [x] Deactivated insurance policies displaying: #2523.
- [x] Supplier credits list sizing: #2525.
- [x] `DemoUserModal` component blocked by incorrect modal: #2546.

### `4.0.3`

- [x] Modal strings not centred. #2556 
- [x] Cash transaction confirm button overlap. #2562.
- [x] Cash transaction toggle too close to modal text. #2568.
- [x] Incorrect conditional in lookback period logic. #2572.

### `4.0.4`

- [x] Time offset bug sync error: #2842.

### `4.0.5`

- [ ] Sorting crash: #2406. 
- [ ] CVE-2020-7598 vulnerability: #2557.

**Comment by joshxg** [comment]
I would think it would be a good idea to get this insurance issue done sooner rather than later. https://github.com/openmsupply/mobile/issues/2433

Also #2406 is a pain - bugsnag has reported a couple of crashes, but have not been able to repro or see the cause.

Would be really great to get both of these into patches

**Comment by joshxg** [comment]
Have just had this bugsnag come through now: https://github.com/openmsupply/mobile/issues/2448

Following the path (there's only one possible), an `ItemBatch` has an undefined `Item` - not great and obviously causing errors. Would be good to fix this, but it is in 3.X - fixing it in `4.0.0` would mean anyone wanting a fix for this needs to upgrade to `4.09` server.. 🤷‍♂ !

**Comment by joshxg** [comment]
Also even more from testing, which is good! #2471 - #2473

**Comment by wlthomson** [comment]
Description updated.

All issues are PRd, with exception of #2406 (not yet replicated) and #2490 (only just added to milestone). All things going well, expecting to release on Monday (9/3).

**Comment by joshxg** [comment]
Have added #2546  to the `4.0.2` patch as I think it's pretty nasty!

**Comment by wlthomson** [comment]
Have updated description with some more `v4.0.3` bugs, plan to release by Friday!
