### ISSUE TITLE
Patient lookup API 

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#2446]
## Description

Epic for managing mobile work for patient lookup API. 

Overview:

- Add an API to desktop which allows mobile to query for patients (e.g. by name, DOB, insurance number). 
- Update the mobile dispensing page to allow prescribers to lookup patients who are not "local" to their store/site.
- Add logic to update the visibility for patient/prescriber which are added to the current store. 
- Update the dispensing wizard to enforce certain constraints when prescribing to these patients, e.g. cannot edit patient details, cannot edit patient insurance etc.

Constraints:

- The prescriber/patient home store should not be changed. 
- The prescriber/patient should be "read-only" on the satellite site:
  - New prescriptions/policies can be created.
  - Existing records cannot be edited (including linked records, e.g. insurance policies).
- Record visibility should be updated on the server on incoming sync (i.e. mobile outgoing sync).

## Issues

- [x] Add patient lookup UI to dispensing page. #2540.
- [x] Add patient lookup modal to dispensing page #2541.
- [x] Add patient lookup logic to dispensing page. #2542.
- [x] Update prescription tabs to enforce read-only constraints for non-local patients. #2543.
- [x] Add patient API network helpers. #2616.
- [x] Add bugsnag to catch runtime API errors. #2632.
- [x] Add onPress logic for selecting records from API search. #2633.
- [x] Update search form components. #2645.
- [x] Add patient API network authentication logic. #2651.
- [x] Move network helper calls to thunks. #2654.
- [x] Add logic for creating insurance policies. #2657.
- [x] Extract patient API record creation helpers. #2664.
- [x] Add insurance policy creation logic thunks. #2678.
- [x] Add response code handling to API network helpers. #2681
- [x] Lookup modal may cause unmounted state changes. #2687.
- [x] Read-only constraints not being consistently applied. #2689.

## Specification docs

- Desktop epic: https://github.com/sussol/msupply/issues/5821.
- Internal wiki (in progress): https://sussol.net/wiki/doku.php/msupply:specifications:customers:lookup_api.
- Discussion issues:  #2544.

**Comment by wlthomson** [comment]
I think I'm missing a bit of background info on this, so if any of this is wrong, let me know.

AFAICS, this functionality can be broken down into 3 components:

1. desktop side API.

- design the API specs (e.g. endpoint, request/response format). 
- add logic for looking up a specified patient (or patients?), and return that patient(s) details in a given format.

2. mobile side UI, logic.

- basic idea is to add a button etc. that allows the user to specify some details to lookup the patient?
- do we want some sort of indicator to the user whether the server is available, e.g. the icon is "greyed out" if the server is not accessible (maybe periodically poll in a similar way to sync)?
- what details do we want the user to query?
- what data do we want to be "read-only" v. writable?

3. changes to existing sync logic (i.e. how to handle patient credit, insurance policies etc.).

- this will probably depend to some degree on the above question re. which data is "read-only" and writable.
- will the patient API cause any potential data integrity issues (e.g. can the patient pay with insurance or credit)?
- based on above, what changes do we need to make to sync to prevent/mitigate these problems? 

@joshxg @mark-prins I think that covers most of the main areas? Anything I've missed?

**Comment by joshxg** [comment]
Had a little bit of discussion here a bit ago -  https://github.com/sussol/org-issues/issues/47 

The main idea is for patients, but I think prescribers are sort of being forgotten about also. 

Quick recap:
*Prescribers*
- Currently we have added a `store_ID` to a prescriber.
- This makes it store data.
- Want to be able to use prescribers in different stores, to remove the number of duplicates.
- pretty simple just with the store ID to determine where it can be editable

*Patients*
- Each patient uses a `supplying_store_id` to mark their home store
- Currently only editable and can only be dispensed to from their home store
- Want to be able to issue scripts to patients from anywhere
- Dispensing to patients introduce some problems: view patients history, drug interactions, repeats and patients credit.

-----------

### Desktop

> Design the API specs (e.g. endpoint, request/response format).
    Add logic for looking up a specified patient (or patients?), and return that patient(s) details in a given format.


Yup - plus I think prescribers



### Mobile
> Basic idea is to add a button etc. that allows the user to specify some details to lookup the patient?

yeah - maybe below the list of patients (i.e. so they have to search first locally, if they cant find it, the buttons there)

> Do we want some sort of indicator to the user whether the server is available, e.g. the icon is "greyed out" if the server is not accessible (maybe periodically poll in a similar way to sync)?

Seems over the top to me

> What details do we want the user to query?

Personally, I think basically use the current form for a patient, with some being required. Then you can just use a bunch of fields to lookup.

Possibly, just names/dobs to start


> What data do we want to be "read-only" v. writable?
 
If not the home store, all read-only. Also need a way to 'swap' home store in the future (I think this is non-trivial - needs to be done through the server with ack's from both stores so there isn't patients stuck in a void)

### Sync

>  This will probably depend to some degree on the above question re. which data is "read-only" and writable.

If we don't sync patient history (their transacts), then there should be no problem with credit - related: https://github.com/sussol/msupply/issues/5490. Drug interactions I have been told we "shouldn't worry about" (also not in mobile). Repeats there are a couple of different options: https://github.com/sussol/msupply/issues/5492 (also not in mobile) - insurance: couple of options (related: https://github.com/sussol/msupply/issues/5493). There are also patient notes (note tab in patient form in desktop) and patient medical records - neither used in mobile and no one seems to care too much about them! 

related issue which went through sync with adrian. Things seem to have slipped since then. This definitely spreads accross repos and is hard to keep up - sorry, too big for one person to be trying to manage!! :( https://github.com/sussol/org-issues/issues/40

> Will the patient API cause any potential data integrity issues (e.g. can the patient pay with insurance or credit)?

I suppose the above answers this, maybe I got confused with the questions

**Comment by wlthomson** [comment]
Update: description updated.

Next steps are to create issues with a bit more info.

Will also need to create a desktop issues for the API (or update https://github.com/sussol/msupply/issues/5697) and possible changes to outgoing sync (e.g. update initial dump to include patients if they have a transaction history).

@mark-prins @joshxg Have I missed anything?

**Comment by joshxg** [comment]
@wlthomson 

What I think is missing is prescribers - they're currently store data (previously system data), so I would have thought that it might be an expectation of users that they are able to assign a prescriber from another store to a script. It would at least limit the amount of maintenance and overhead of merging, if you were able to lookup prescribers from different stores

Also: Transferring of a home store (for both patients and prescribers)

**Comment by wlthomson** [comment]
>  so I would have thought that it might be an expectation of users that they are able to assign a prescriber from another store to a script.

Hm, my thinking was that it would be quite unusual for prescribers to be "roaming". Would it make sense to assign a prescriber from another store to a script? Wouldn't it make more sense to update the prescribers home store if they "move" to another health centre? @mark-prins Thoughts?

> Also: Transferring of a home store (for both patients and prescribers)

Could you elaborate on this? Is this something we want to do via the API?

**Comment by joshxg** [comment]
> Wouldn't it make more sense to update the prescribers home store if they "move" to another health centre?

Yeah. You'd need to lookup the prescriber, somehow, though.

> Could you elaborate on this? Is this something we want to do via the API?

There is no way to transfer a patients home store or a prescribers `store_ID` currently - we need a way - this API seemed like the most logical place for this feature

**Comment by wlthomson** [comment]
Sorry, to clarify, my thinking was that this might be done on the desktop side. I guess it comes down to how far IC want to micromanage their health centres. I assumed that a prescriber changing health centre might be something that would be updated higher up the chain rather than by the health centres themselves. If not, then I agree that adding this feature to mobile + API seems like a good idea.

**Comment by joshxg** [comment]
@wlthomson to be fair I don't have enough domain knowledge. My thoughts are primarily around reducing the number of duplicate records to help with data integrity

**Comment by mark-prins** [comment]
> @mark-prins Thoughts?

uh oh.

I was thinking that a prescriber would be local, but I'm conflating a 'dispensing pharmacist' with a prescriber and I suppose that there is a possibility that a patient would be prescribed elsewhere and turn up to a health centre with a script from a prescriber not registered locally.

which means that all the patient lookup tasks have to be duplicated for the prescribers too

**Comment by mark-prins** [comment]
transfer of home store though.. we said that would be later. I'm not convinced of the immediate need for that. could we look at it as a later improvement?

**Comment by joshxg** [comment]
> could we look at it as a later improvement?

Only thing I would say is that the earlier we do it the less duplicates we're likely to have which is just an all-round general improvement!

**Comment by wlthomson** [comment]
OK so, to summarise:

- general agreement on the main patient api tasks.
- add prescribers to look up. 
- home store transfer definitely not off the table, but on the back burner for now.

**Comment by adrianwb** [comment]
From what I understand, I think it's best to leave the merging/transferring of patients/prescribers to the desktop side of things as that seems to me to be quite a high-level management kind of thing. Maybe simplest to keep both of them centralised, but with some mechanism where a site (mobile or desktop) can request a patient/prescriber transfer, or initiate a merge (where both records belong to the same store)?

As long as mobile can lookup patients/prescribers and issue a basic prescription, then that's the main thing - the home store only restricts where the patient/prescriber details can be edited, not where they can be used.

If mobile cannot access the central server, then obviously the lookup won't work and they'll just have to create a potential duplicate - hence the need for merging.

**Comment by adrianwb** [comment]
And of course, whatever way the lookup is implemented for mobile, the same thing will need to be done for desktop dispensary sites...

**Comment by wlthomson** [comment]
Update: have updated description with progress.

Have updated `v5` with a target for 13/04, plan is to get this work PRed in by Friday.

**Comment by wlthomson** [comment]
Feature merged in #2732.

For further discussion and documentation see `v5.0.0` release discussion (#2445).
