### ISSUE TITLE
6.0.0 Release Discussion

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2722]
## RELEASE VERSION

v6.0.0

### SUMMARY

This release will be primarily focussed on the new vaccine module.

The development deadline is 5th October

### Refactors/Enhancements

- [x] Spinner when creating a program requisition: #2294.
- [x] Highlight the row currently being edited: #1657
- [x] Number of days in a month consolidated to 365/12 #3131
- [x] The login screen should show the store name #3050
- [x] All modals should cover the full screen #3209 

### Features

- [x] Vaccines module: #1353. [DELAYED until next release]
- [x] Program based customer requisitions #3128 .
- [x] Search items by code within prescriptions #3130 

### Bugs
- [x] Prescribers are not merged: #2991.
- [x] Inconsistent formatting of period dates: #3034.
- [x] Android crashes when there are a lot of text inputs: #3154 
- [x] Outgoing Name records can halt sync #3237
- [x] No results when looking up Prescribers #3215

### Translations

- [x] Burmese/Myanmar vaccine strings: #2993.

## Documentation

- https://docs.msupply.foundation/en:mobile:user_guide:customer_requisitions
- https://docs.msupply.foundation/en:mobile:user_guide:cold_chain_equipment

**Comment by joshxg** [comment]
awesome thanks @wlthomson 

The vaccines feature is progressing well and can be tracked at #1353 

I suggest we move all the issues which didn't quite make it into 5.0 into here when we're ready. Then we can see what we're working with - maybe there will be room for a few refactors if we're lucky! 🎉

**Comment by wlthomson** [comment]
Nice!

The current thinking is to skip straight to `v6.0.0` from `v5.0.0` (no minors or patches), as it's looking like vaccine work will be not too far away (from discussion with @joshxg).

Plan is to move everything not completed in `v5`, and also the top priority lookup API issues here. Idea would be to get this released sometime towards end of this week or next week, at which point issues can be migrated to `v6.1.0` minor (and any future urgent bugs to patches, e.g. `v6.0.1`).

**Comment by wlthomson** [comment]
Update:

Testers have done a really good job on `v5.0.0`... more issues than expected! Looking like `v5.0.0` will be released next week (starting 11/05). Plan is still to go straight to `v6.0.0`, so at that point anything which isn't a release blocker will get moved over here!

**Comment by joshxg** [comment]
Sorry for the silence!

I've released the first RC version for 6.0.0 here: https://github.com/openmsupply/mobile/releases/tag/v6.0.0-rc0


There are draft docs in our internal google doc here: https://docs.google.com/document/d/1UPa2HNmUhithGoK0anmrQAKxkxcHpnJqG6W2H6sQZD4/edit

We are still waiting for at least 4.12 to be released for desktop. However Alain is looking to do some testing shortly as he has ordered a BlueMaestro sensor to test with 🎉 🎉 🎉 

Given we are so far behind schedule on this release, once Alain has tested and 4.12 is released, I think we will ship 6.0.0 with or without the remaining issues

**Comment by wlthomson** [comment]
> Given we are so far behind schedule on this release, once Alain has tested and 4.12 is released, I think we will ship 6.0.0 with or without the remaining issues.

Sounds good 🎉.

Most mobile work has gone into `v5.0.X` patches, so I think this release is going to be 99% vaccines!

**Comment by joshxg** [comment]
Another update:

Alain has gone on holiday!

We have sent tablets and sensors to testers in ivory coast who will give the new version a spin - hopefully after that we can release, but it means this is continuing to be on hold for awhile!

**Comment by joshxg** [comment]
Update:

After a bit of a hiatus, there is a bit more being added to 6.0: [Manually created, program based customer requisitions!](https://github.com/openmsupply/mobile/issues/3128)

- This work is being started immediately.
- Alain is still testing Vaccines module. However, it appears that we may not officially release this module with the 6.0 release, anymore. We will however ensure it makes it into the code base, finally! We are waiting for WHO approval for the temperature sensor before making an official announcement of release, which may not be receieved before needing to release 6.0 for JSI and the customer requisition functionality.

The new deadline for this release is now 5th October!

**Comment by joshxg** [comment]
Update:

After more deadlines of other projects and additional requirements being added to the vaccine module, the decision has been made to disable the vaccine module for the 6.0 release which is required to delivery program customer requisitions.

https://github.com/openmsupply/mobile/issues/3175

Vaccine module will be re-enabled in the next release

**Comment by wlthomson** [comment]
@joshxg Any updated ETA on `v6` and/or any help needed?

**Comment by joshxg** [comment]
Have had Bijay, Ana and Mai test the customer requisition module - all is looking OK. 

Looking to release as soon as I have time to do general testing of the app (just double checking everything is still OK/regression testing)

**Comment by joshxg** [comment]
Sorry, I know this has taken a long time. @alainsussol is doing some last minute testing and so will give the green (or red??) light soon!

**Comment by joshxg** [comment]
Just waiting for this last PR for 6.0 : https://github.com/openmsupply/mobile/pull/3257 - totally releasing tomorrow!

**Comment by joshxg** [comment]
Released, finally! 

Thanks to everyone involved :)
