### ISSUE TITLE
5.1.0 Release Discussion

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#2836]
## RELEASE VERSION

v5.1.0

### SUMMARY

`v5.1.0` is a short release for bridging any minor features and bugs for `v5`. As the `v6` major release is targetted for release within next few weeks, this issue should be reserved for minor refactors and/or fixes for existing functionality.

The development deadline is aimed for around a week, but may be longer or shorter depending on user feedback and testing capacity.

UPDATE: development deadline pushed back a lot... a lot more testing and omsupply tasks than anticipated. Aiming for 19/06, including Burma translations. 

### Refactors/Enhancements

- [x] Cash register reducer: #2022.
- [x] Reduce bugsnagging in fetch hook: #2748.
- [x] Set insurance form policy family number is not a required field. #2918.
- [x] Update insurance form policy number ordering. #2919.

### Bugs

- [x] Expiration date not always correct: #2770.
- [x] Patient created on mobile store remains editable after home store is updated: #2943.
- [x] Dates are synced to desktop without timezone offset: #2946.
- [x] Patient gender not correctly syncing to desktop. #2989.
- [x] Insurance discount rate not displaying correctly in payment summary. #2994.

### Translations

- [x] Add Myanmar to language selection: #2949.
- [x] Burmese/Myanmar auth strings: #2950.
- [x] Burmese/Myanmar button strings: #2951.
- [x] Burmese/Myanmar dispensing strings: #2958.
- [x] Burmese/Myanmar form strings: #2962.
- [x] Burmese/Myanmar general strings: #2964.
- [x] Burmese/Myanmar modal strings #2966.
- [x] Burmese/Myanmar navigation string translations: #2967.
- [x] Burmese/Myanmar page info string translations: #2968.
- [x] Burmese/Myanmar program string translations: #2969.
- [x] Burmese/Myanmar sync strings: #2971
- [x] Burmese/Myanmar table strings: #2972.
- [x] Burmese/Myanmar validation string translations: #2974.

### TESTING

- [ ] Stocktake edit page: #1242.

**Comment by wlthomson** [comment]
Update:

Just for clarification: the turnaround between `v5` and `v6` should hopefully be quite quick (plan was to not have a minor in-between... but ended up being a bit more fixes in `v5` than expected!), so this release will hopefully be a small one focussed only a few refactors/tidyups which didn't make it into `v5`.

**Comment by wlthomson** [comment]
Update:

Going to go ahead and release as planned. AFAIK vaccines isn't too far away, so can bump remaining issues to `v6` (or later).

@joshxg Sound good?

**Comment by joshxg** [comment]
@wlthomson 

Great, sounds good. Need to wait for 4.12 for vaccines, which should be a couple/few weeks away.

**Comment by wlthomson** [comment]
Update:

`v5.1.0` is released! :tada:

Closing this out. All undone issues bumped to `v6.0.0` discussion [here](https://github.com/openmsupply/mobile/issues/2722).

`v5.1.X` patch discussion [here](https://github.com/openmsupply/mobile/issues/3001).
