### ISSUE TITLE
5.1.X Release Discussion

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/mobile#3001]
Major release discussion: #2445.
Minor Release discussion: #2836.

This issue is for discussions on issues with the 5.1.X release.

# Releases

### `5.1.1`

- [x] Returning null from outgoing sync utilities: #2997.
- [x] Insurance policies from lookup API are inactive: #3008.

### `5.1.2`

- [x] Patient name is undefined on back navigation: #2945.
- [x] Insurance policies without personal policy number are incorrectly formatted: #3015.
- [x] Insurance policies with personal policy number are incorrectly formatted: #3016.
- [x] Insurance form incorrectly enforces personal instead of family policy number: #3018.
- [x] Mobile sync blanking out some transaction fields: https://github.com/openmsupply/mobile/issues/3056
- [x] Insurance policy validation allows policies without family numbers: #3072.
- [x] App crashing on sorting stock take lines: #3081.
- [x] Requisition syncing without requisition lines: #3084.
- [x] Stock transfers syncing without linked transaction lines: #3085.
- [x] Removing stock take causes app crash: #3099.
- [x] Deleted stock take from mobile not deleted on desktop store: #3103.
- [x] Add migration code to remove invalid sync out records: #3109.
- [x] App crashing on deleting finalised supplier invoice data: #3094.
- [x] App crashing on deleting finalised customer invoice data: #3096.
