### ISSUE TITLE
Program based Customer Requisitions

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3128]
## Is your feature request related to a problem? Please describe.

JSI Require program-based customer requisitions. Problem is, they're not implemented, yet.

### Main tasks overview:
- Add `name_tag_join`/`name_tag` to schema/incoming sync
- Change Supplier Requisition to use `name_tag`
- Change "By Program Modal" for Customer Requisitions
- Add New Requisition button to Customer Requisitions Page
- Add "Program" column to Customer Requisitions Page *Didn't discuss*
- Add Program-based Customer Requisition column changes (All described in tests)
- Add Program-based Customer Requisition page info changes (All described in tests)
- Change usage formula to use `365/12` instead of `30`

Google sheet for columns spec: https://docs.google.com/spreadsheets/d/1sEiR9BTVQJ52kLPoVjMGOi8EghRRSTHkDlYkkNUDV20/edit#gid=0

### Implementation issues:
- [x] Add `name_tag`/`name_tag_join` to schema/incoming sync
    - ISSUE: #3134 
    - PR: #3136 
- [x] Change Supplier Requisition to use `name_tag`
    - ISSUE: #3135
    - PR: #3138
- [x] Change "By Program Modal" for Customer Requisitions
    - ISSUE: #3132
    - PR: #3139 
- [x] Add New Requisition button to Customer Requisitions Page
    - ISSUE: #3133 
    - PR: #3140
- [x] Add Program-based Customer Requisition column changes (All described in tests)
    - ISSUE: #3141 
    - PR: #3142
- [x] Add Customer Requisition AMC formula item detail
    - ISSUE: #3148  
    - PR: #3149 
- [x] Add Program-based Customer Requisition page info changes (All described in tests)
    - ISSUE: #3144 
    - PR: #3150 
- [x] Add new customer requisition fields to incoming and outgoing sync
    - ISSUE: #3143 
    - PR: #3151 
- [x] Change usage formula to use `365/12` instead of `30`
    - ISSUE: #3131 
    - PR: #3137 
- [ ] TESTING
    - Customer Requisitions: #1243
    - Customer Requisition: #1244 
- [x] Update documentation
    - Draft doc: https://docs.google.com/document/d/1_n3IgsxtE08sP1aw--KmIyP3rYe9kL_Y2KAByvCHRE4/edit

**Comment by joshxg** [comment]
@craigdrown @andreievg 

First question before moving forward anymore: Is this for normal customer based requisitions, or program based also?

**Comment by craigdrown** [comment]
@joshxg program based, as need to access MOS targets from program data

**Comment by craigdrown** [comment]
@joshxg The requirement for a "date created" field: suggest we use requisition.date_stock_take (which is really correct- that's the date that is relevant, seeing the form is a stocktake. Default to today, but editable. Thanks.
(n.b. There is another "Date requisition entered" field that is not editable and auto-populated)

**Comment by joshxg** [comment]
@craigdrown @andreievg 

> program based, as need to access MOS targets from program data

Of course, thanks.

`Assumptions from this, correct me if wrong:`

*When creating a program based customer requisition, select*:
- A program [Found through `[name]` -> `[name_tag_join]` -> `[name_tag]` -> `[list_master]programSettings.storeTag`]
- A name: "You can enter any name that is visible to you" : Don't exclude *any* name (Thought this would be Customer names types who are not patient)
- A Period: Assuming required no different to a supplier requisition
- An Order type: Assuming required (Needed for max MOS), defined within `Program settings` respecting the current rules for threshold MOS, emergency orders, max orders per period, maximum lines, 


`Next question:`

- Are we implementing the ability for all users to create a normal customer requisition, if there are no programs defined?

**Comment by craigdrown** [comment]
>     * Don't exclude _any_ name (Thought this would be Customer names types who are not patient)
@joshxg that was implied ;-)  - so yes, any visible customer who isn't a patient.
Order type: default to normal until there's been a normal order already in the period, then default to emergency?

**Comment by andreievg** [comment]
> A program [Found through [name] -> [name_tag_join] -> [name_tag] -> [list_master]programSettings.storeTag]

Also, only use `list_master` linked to the name.

> Are we implementing the ability for all users to create a normal customer requisition, if there are no programs defined?

I don't see this being a use case for JSI requirements (name should still be selectable but message that no programs are linked to the name)

For Ivory Coast we are allowing response/customer requisitions being made for name that are also stores, I feel ify about this. Would suggest 'yes' but with a visible warning.

**Comment by joshxg** [comment]
Thanks!

> The requirement for a "date created" field: suggest we use requisition.date_stock_take (which is correct- that's the date that is relevant, seeing the form is a stocktake).
Default to today, but editable. Thanks.
(n.b. There is another "Date requisition entered" field that is not editable and auto-populated)

This will be newly added to mobile: "Today" being the date the requisition is first created? Is there validation on valid dates? (Not before 'today'? Not before 'date requisition entered'?)

> Order type: default to normal until there's been a normal order already in the period, then default to emergency?

👍 

> I don't see this being a use case for JSI requirements (name should still be selectable but message that no programs are linked to the name)

Still not clear on the behaviour for when there are *no* programs defined (Current supplier requisition: Add requisition has two behaviours dependent on if there are *any* programs defined: Open program modal to create a program-based requisition, or not. Current customer requisition: can't create at all) at all (Behaviour for our existing users) - able to create non-program based now? Or, if you don't have programs defined, still can't create?

> name should still be selectable but message that no programs are linked to the name

Sure, can do. Just FYI: for supplier requisition there is a toggle on the modal: Program/General, and you select the program first. So, the supplier would not show up, you would have to go to the General tab.

> For Ivory Coast we are allowing response/customer requisitions being made for name that are also stores, I feel ify about this. Would suggest 'yes' but with a visible warning.

So, when creating a customer requisition for a `[name]` which is both a `customer` and has a related `[store]` record (Is there some other field which indicates this?), show some sort of warning *note: mobile does not currently store [Store] records*

**Comment by joshxg** [comment]
Questions from email: Re: UNFPA Mobile Work by 30 November 2020

> Months in period: technically (Days in period / Days in month) - I think we’ve standardised on “365/12” for days in a month?

Mobile uses 30 days for a month.

Possible options: 
- change the app to use 365/12 for all clients
- continue using 30 days
- customer chosen preference
- unique formulas per client

**Comment by joshxg** [comment]
@andreievg @craigdrown @Chris-Petty 

Trying to conclude/summaries meetings/discussions/specs/requirements/whatever:

- Have updated the [customer requisitions](https://github.com/openmsupply/mobile/issues/1243) /[customer requisition](https://github.com/openmsupply/mobile/issues/1244) testing templates (below) to reflect the changes to be made. 
- I will use this as the 'spec'/'requirements' moving forward. 
- I know it's a lot to look through, but if you could give it a read and if you see anything that you are not happy with or would like to change, please let me know.

### Main task list:
- [ ] Add `name_tag` to schema/incoming sync
- [ ] Add `name_tag_join` to schema/incoming sync
- [ ] Change Supplier Requisition to use `name_tag`
- [ ] Create Customer Requisition "By Program Modal"
- [ ] Add New Requisition button to Customer Requisitions Page
- [ ] Add "Program" column to Customer Requisitions Page *Didn't discuss*
- [ ] Add Program-based Customer Requisition page changes (All described in tests)
- [ ] Change usage formula to use `365/12` instead of `30`

## Customer Requisitions Page [List of all customer requisitions]

CHANGES:

### Button
- [ ] New Requisition
    - [ ] Clicking on this button opens a "By Program Modal" (More detail below)

### Table
Additional Column:
- [ ] Program
    - [ ] Header Name: Program
    - [ ] Sortable (And sorts correctly)
    - [ ] NOT Editable
    - [ ] Displays the name of the program for the requisition

### By Program Modal
- [ ] Must select steps in order: customer, program, period, order type
- [ ] Customer Step - Can choose any customer name who is not a patient
- [ ] Customer Step - There is a warning when selecting a customer who is also a store.
- [ ] Program Step - Can choose any program where there exists a `name_tag_join` record for the chosen `name` and `name_tag` and the program is visible in the mobile store.
- [ ] Period - Can choose any period that is related to the `periodSchedule`, defined in the `masterList.programSettings.storeTag` which matches the `name_tag` from the selected customer [The first arbitrary storeTag/name_tag matching is used]
- [ ] Period step - Periods, when being selected show the correct details (number of requisitions etc.)
- [ ] Order type step - Can choose any order type defined in the `masterList.programSettings.storeTag` where the number of orders in the period is less than the max number of orders for the order type.
- [ ] Order types step - when being selected show the correct details (MOS etc.)
- [ ] Can back pedal steps, where the progress is adjusted correctly
- [ ] there is no ability to create a 'general' requisition
- [ ] OK is enabled when all steps are complete
- [ ] closing the modal, closes the modal 
- [ ] programs items are added to the created requisition
    
    
## Customer Requisition Page

### NAVIGATION

- [ ] Can navigate to this page through the customer requisitions page (clicking on a row) when the customer requisition has a PROGRAM related
- [ ] Top left displays '"Requisition X"' where `X` is the serial number for this requisition
- [ ] Can navigate to this page through creating a NEW REQUISITION

### SYNC

- [ ] Changes made to this customer requisition are synced to desktop (to trigger, edit a comment and sync)

### Table

- [ ] Lists all items which are in the program selected for this requisition
- [ ] Initial sort is by item name, in ascending order

#### Row Press

- [ ] Pressing on a row has no effect (except for editable cells)
    
#### Filtering

- [ ] items are filtered by item name or code
- [ ] Filtering is cleared when the search term is cleared

#### Toggle

- [ ] Toggling the table toggles between two different column sets (defined below)
- [ ] Toggling between the column sets correctly displays values/rows (enter a quantity in a row for a column, then toggle the column set and toggle back - the value should still be set)
- [ ] Column set A: [Item Name, Item Code, Current Stock, Their Current Stock, Monthly Usage, Suggested Quantity, Requested Quantity]
- [ ] Column set B: [Item Name, Item Code, Supply This Invoice, Days out of Stock, Opening Stock, Closing Stock, Adjustments, Receipts]

#### Columns 

- [ ] **Item code**
    - [ ] Header Name: Item Code
    - [ ] In Column set A and B 
    - [ ] Sortable (and sorts correctly)
    - [ ] Items have the correct Item Code
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting
    - [ ] NOT editable.
    - [ ] Left aligned
- [ ] **Item Name**
    - [ ] Header name: Item Name
    - [ ] In Column set A and B 
    - [ ] Sortable (and sorts correctly)
    - [ ] Item names are correct
    - [ ] Sorting icon updates correctly to indicate ascending/descending and no sorting.
    - [ ] NOT editable
    - [ ] Text overflow handled (create an item name that is very long)
    - [ ] Left aligned
- [ ] **Current Stock**
    - [ ] Header name: Our Current Stock
    - [ ] In Column set A
    - [ ] Sortable (and sorts correctly).
    - [ ] NOT Editable
    - [ ] Right aligned
    - [ ] Displays the current stock for that item (should match what is displayed in current stock page)
    - [ ] Is updated when adjustments are made and requisition is revisited (check current stock levels -> create a finalised SI -> give the store more stock for an item in the requisition)
- [ ] **Their Current Stock**
    - [ ] Header Name: Their Current Stock
    - [ ] In Column set A
    - [ ] Sortable (and sorts correctly)
    - [ ] EDITABLE unless finalised.
    - [ ] Right aligned
    - [ ] Initial default value: 0
- [ ] **Monthly usage**
    - [ ] Header Name: Monthly Usage
    - [ ] In Column set A 
    - [ ] Sortable (and sorts correctly).
    - [ ] NOT Editable
    - [ ] Right aligned
    - [ ] Displays the customer monthly usage for that item
- [ ] **Suggested Quantity**
    - [ ] Header Name: Suggested Quantity
    - [ ] In Column set A 
    - [ ] Sortable (and sorts correctly).
    - [ ] NOT Editable
    - [ ] Right aligned
    - [ ] Displays the suggested quantity for that item
    - [ ] Suggested quantity is correctly calculated: `ceil(max(customers monthly usage * months to supply - their stock on Hand, 0))`
- [ ] **Requested Quantity**
    - [ ] Header Name: Requested Quantity
    - [ ] In Column set B
    - [ ] Sortable (and sorts correctly)
    - [ ] Right aligned
    - [ ] EDITABLE unless finalised.
    - [ ] Validation: 0 <= RQ <= 9999999
    - [ ] Default: empty
    - [ ] NOT required field
- [ ] **Supply this invoice**
    - [ ] Column name: Supply this Invoice
    - [ ] In Column set B
    - [ ] Sortable (and sorts correctly).
    - [ ] Right aligned
    - [ ] EDITABLE unless finalised.
    - [ ] Default: 0
    - [ ] Validation: (SQ = Supplied Quantity): 0 <= SQ <= 9999999
    - [ ] Validation: Cannot enter a value greater than the current stock on hand for this store
- [ ] **Days out of stock [DOoS = Days Out of Stock]** 
    - [ ] Column name: Days out of Stock
    - [ ] In Column set B
    - [ ] Sortable (and sorts correctly).
    - [ ] Right aligned
    - [ ] EDITABLE unless finalised.
    - [ ] Default: 0
    - [ ] Validation: DOos Quantity): 0 <= SQ <= ???
- [ ] **Opening Stock** 
    - [ ] Column name: Opening Stock
    - [ ] In Column set B
    - [ ] Sortable (and sorts correctly).
    - [ ] Right aligned
    - [ ] EDITABLE unless finalised.
    - [ ] Default: Equal to the CLOSING stock of the LAST requisition entered for that customer
- [ ] **Closing Stock** 
    - [ ] Column name: Closing Stock [IS THIS THE SAME AS THEIR STOCK ??]
    - [ ] In Column set B
    - [ ] Sortable (and sorts correctly).
    - [ ] Right aligned
    - [ ] EDITABLE unless finalised.
    - [ ] Default: 0
- [ ] **Adjustments** 
    - [ ] Column name: Adjustments
    - [ ] In Column set B
    - [ ] Sortable (and sorts correctly).
    - [ ] Right aligned
    - [ ] EDITABLE unless finalised.
    - [ ] Default: ??
- [ ] **Receipts** 
    - [ ] Column name: Receipts
    - [ ] In Column set B
    - [ ] Sortable (and sorts correctly).
    - [ ] Right aligned
    - [ ] EDITABLE unless finalised.
    - [ ] Default: Sum of all `TransactionBatch.totalQuantity` where `TransactionBatch.transaction === 'customer_invoice` and `TransactionBatch.transaction.otherParty === the customer for this requisition`

### Buttons

- [ ] `"Use Suggested Quantity"` 
  - [ ] Button is displayed
  - [ ] On press, sets `"Supply this invoice`" to equal `"Suggested Quantity"` for all rows
- [ ] `"Use Required Quantity"`
  - [ ] Button is displayed
  - [ ] On press, sets `"Supply this invoice"` to equal `"Requested quantity"` for all rows

### Page Info

- [ ] **Program**
    - [ ] Displays the NAME of the program this requisition is for.
- [ ] **Months Stock**
    - [ ] Displays the number of months this requisition is for.
    - [ ] Is defined by the order type used to create the requisition [max MOS]
- [ ] **Entry Date**
    - [ ] Shows the correct entry date for this requisition
- [ ] **Created Date**
    - [ ] Enterable Date which CANNOT be less than Entry Date.
    - [ ] Clicking opens a date picker [See modals]
- [ ] **Customer**
    - [ ] Shows the correct customer for this requisition
- [ ] **Comment**
    - [ ] Displays the comment field for this requisition correctly 
    - [ ] Clicking opens the comment modal (see modals) 
    - [ ] Is disabled when finalised
- [ ] **Period**
    - [ ] Displays the PERIOD field for this requisition correctly 
    - [ ] NOT editable
    - [ ] Displays: {DD/MM/YYYY - DD/MM/YYYY} i.e 1/1/1970 - 21/9/2020
    - [ ] Is disabled when finalised
- [ ] **Order Type**
    - [ ] Displays the NAME of the ORder Type selected when the requisition was created
    - [ ] NOT editable
    - [ ] Displays: {DD/MM/YYYY - DD/MM/YYYY} i.e 1/1/1970 - 21/9/2020
    - [ ] Is disabled when finalised

### Modals

- [ ] **Comment**
    - [ ] Title is `"Edit the requisition comment"`
    - [ ] If there is already a comment, it is entered already
    - [ ] Empty if no comment
    - [ ] Entering a comment and pressing OK saves the comment correctly
    - [ ] closing the modal closes the modal
- [ ] **Created Date**
    - [ ] Shows a DATE PICKER, allowing a date to be selected no less than `Entry Date`

### Finalizing

- [ ] Pressing finalize opens a confirmation dialog warning about locking the invoice and that finalising this requisition will create a finalized customer invoice
- [ ] Cancelling the confirmation cancels finalising the requisition
- [ ] Confirming the confirmation dialog finalises the requisition, locking all edits (as listed above) - - [ ] Finalising the requisition creates a finalised customer invoice related to this requisition
- [ ] Finalizing the requisition correctly sets the status of the requisition to finalised.
- [ ] All items with a quantity of `0` ARE NOT pruned from the requisition 
- [ ] All items with a quantity of `0` ARE pruned from the customer invoice

### Desktop Upgrade:
- [ ] When upgrading, mobile adds a `[message]` record to the sync queue which syncs to desktop
- [ ] Desktop, after receiving the [message] record, adds the following to the `sync_out` queue for the mobile store:
    - [ ] All `[store]` records
    - [ ] All `[name_tag]` records
    - [ ] All `[name_tag_join]` records
    - [ ] The `[name]` 


**NOTE: Will need to retest Supplier Requisitions Page, By program modal specifically to ensure behaviour is the same with the small refactors to using `name_tag`**

**Comment by andreievg** [comment]
Thanks for that Josh, it's looking good, a few comments, what do you think ?

**Customer Requisitions Page:**
- Was wondering if we need a way to distinguish between Requisitions entered vs received via sync

**By Program Modal**
- Program step, also the program should be linked to the name

**NAVIGATION**
> Can navigate to this page through the customer requisitions page (clicking on a row) when the customer requisition has a PROGRAM related

Not sure what this means, can currently navigate to customer requisition when clicking on a row (why the extra `when the customer requisition has a PROGRAM related ?)

**Toggle**
> Toggling between the column sets correctly displays values/rows (enter a quantity in a row for a column, then toggle the column set and toggle back - the value should still be set) 

I would imagine toggle will just be toggling visibility ? i.e. rows position etc will still be the same ?

Toggle and extra columns view only visible when requisition is program requisition ?

> Column set A: [Item Name, Item Code, Current Stock, Their Current Stock, Monthly Usage, Suggested Quantity, Requested Quantity]

>  Column set B: [Item Name, Item Code, Supply This Invoice, Days out of Stock, Opening Stock, Closing Stock, Adjustments, Receipts, Consumption]

My vote is to keep existing 'view' and add another 'toggle' view for extra bits (probably start with extra bits for program requisitions ?) https://docs.msupply.foundation/en:mobile:user_guide:customer_requisitions, requested quantity editable.

Thus the extra view becomes:  [Item Name, Item Code, Opening, Incoming, Adjustments, Issue, Closing, DOS, Requested]

THIER STOCK = closing balance

**Columns**

` Current Stock`
> Header name: Our Current Stock

Just `Our Stock` Right ?

`Their Current Stock`

> Header Name: Their Current Stock

Maybe :
```
Their Stock
(Closing)
```

Also `not editable` (calculated)

`Supply This Invoice`

Just FYI shouldn't need to make any changes here

`Receipt`

> Default: Sum of all TransactionBatch.totalQuantity where TransactionBatch.transaction === 'customer_invoice and TransactionBatch.transaction.otherParty === the customer for this requisition

This would be for the period of the requisition ?

`Consumption`

**Desktop Upgrade:**

>  All [store] records

Hmm not sure why

> The [name] 

Would assume this is the name of the mobile store ? Was wondering why.

Also I am not 100% sure how programs are 'integrated' in sync, so would just want to add that if only mobile stores's program setting are currently integrated, we would need to change that and would need to 

NOTE: since we are changing to name_tag throughout the app for programSettings, would suggest, adding logic to check storeTag and nameTag on program settings. (i.e. if/when we move to programSettings.nameTag, no extra work would be required on mobile).

**Data Entry Validation:**

We want to restrict negative closing stock calculation (starting + incoming -/+ adjustments - issue = closing), this would mean restricting input on starting, incoming, adjustments, issue. How do we warn user about it ? M 

Do we have ability to enter negative numbers btw ? Would it be easier to have two columns for adjustments ?

**Editable non editable**

I was hoping that the normal column set (exist one), would still remain as is, there is an editable column there though 'requested', was wondering if it's bad UI practice to allow it being editable in one place and not the other.

So the idea was to have editable fields in the 'first' toggled column set, this is basically the part where users goes through and inputs data from the paper based form, they then can switch to second column set and do the issue part. 

** Calculations **

The reason to put closing balance in the first column set was to show the calculation of closing stock while data entry happens (and to help them with validation issues). This would mean the toast for validation error might need to say the formula, and the numbers that are used.

AMC calculation won't be visible anywhere, would be great to help user see the AMC calculation when row is pressed (in a modal)

**Comment by joshxg** [comment]
> Was wondering if we need a way to distinguish between Requisitions entered vs received via sync

We don't for any other page. I think it's a good idea but a little out of scope for this feature?

> Not sure what this means, can currently navigate to customer requisition when clicking on a row (why the extra `when the customer requisition has a PROGRAM related ?)

Not sure either. Oops

> I would imagine toggle will just be toggling visibility ? i.e. rows position etc will still be the same ?

This is what I am trying to describe in the test case - to be tested for: Ensuring we are not losing values entered when toggling between

> Toggle and extra columns view only visible when requisition is program requisition ?

Cool, yup

> Thus the extra view becomes: [Item Name, Item Code, Opening, Incoming, Adjustments, Issue, Closing, DOS, Requested]

Cool - I think I got a little confused :)

> Just Our Stock Right ?

oops, thanks

> Maybe :
> Their Stock
> (Closing)
> Also not editable (calculated)

Cool

> This would be for the period of the requisition ?

Yup. Adding clarity, thanks

> All [store] records
> The [name]

- Store records: Was for determining if names were stores but forgot you let me know it's on the `type` field
- Name record: Forgot we use a join table!
So these aren't needed.


> Also I am not 100% sure how programs are 'integrated' in sync, so would just want to add that if only mobile stores's program setting are currently integrated, we would need to change that and would need to

Not 100% sure on what this means, but we store `programSettings` as a string on every master list record, and we have all master lists on mobile


> We want to restrict negative closing stock calculation (starting + incoming -/+ adjustments - issue = closing), this would mean restricting input on starting, incoming, adjustments, issue. How do we warn user about it ? M

Yeah this is tough - my only suggestion is `Toasts` at the moment!

> Do we have ability to enter negative numbers btw ? Would it be easier to have two columns for adjustments ?

Negatives will be fine

> was wondering if it's bad UI practice to allow it being editable in one place and not the other.

I think for preferences, where the user will not really know of 'the other way' it is OK?

> This would mean the toast for validation error might need to say the formula, and the numbers that are used.

Sure - although the toast doesn't show up for *that* long, to fully understand I think it will have to do, for now, and we can try to think of better solutions..?

> AMC calculation won't be visible anywhere, would be great to help user see the AMC calculation when row is pressed (in a modal)

Can do

**Comment by joshxg** [comment]
Tried to make this easy to read.. I didn't know what platform to use. It's a lot of information, so it's hard. Might be easier to edit this comment -> copy + paste into VSCode - it seems more nicely formatted there or a pdf..: [reqs.html.pdf](https://github.com/openmsupply/mobile/files/5258858/reqs.html.pdf) .... or a google sheet: https://docs.google.com/spreadsheets/d/1sEiR9BTVQJ52kLPoVjMGOi8EghRRSTHkDlYkkNUDV20/edit#gid=0

🤷 


Updated columns: 

- Column set A: [Item Name, Item Code, Our Stock, Their Stock (= Closing Stock), Monthly Usage, Suggested Quantity, Supply This Invoice]
- Column set B: [Item Name, Item Code, Opening Stock, Adjustments, Receipts, Closing Stock, Consumption, Days out of Stock, Requested Quantity]

For saving values:


| Column             | Column Set | Header              | Editable | Validation rule                                                                                           | Default                                                                                                                                                                                                                                                                                                                                                                 | calculation                                                                                        | aligned | Mobile field                           | Desktop field                            | comment                                      |
|--------------------|------------|---------------------|----------|-----------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------|---------|----------------------------------------|------------------------------------------|----------------------------------------------|
| Our Stock          | A          | Our Stock           | No       | N/A                                                                                                       | N/A                                                                                                                                                                                                                                                                                                                                                                     | Sum of all the underlying items item batch  numberOfPacks * packSize                               | right   | N/A                                    | N/A                                      |                                              |
| Their Stock        | A          | Their stock         | No       | N/A                                                                                                       | N/A                                                                                                                                                                                                                                                                                                                                                                     | open + incoming + outgoing + adjustments                                                           | right   | RequisitionItem.stockOnHand            | [requisition_line]stock_on_hand          |                                              |
| Monthly Usage      | A          | Monthly Usage       | No       | N/A                                                                                                       | N/A                                                                                                                                                                                                                                                                                                                                                                     | Consumption / (Days in period / (365/12)) * (Days in Period / (Days in Period-Days out of Stock) ) | right   | RequisitionItem.dailyUsage (Divided    | [requisition_line]daily_usage            | Multiply by 365/12 when displaying in the UI |
| Suggested Quantity | A          | Suggested           | No       | N/A                                                                                                       | N/A                                                                                                                                                                                                                                                                                                                                                                     | Math.ceil(Math.max(this.dailyUsage*daysToSupply - this.stockOnHand, 0)                             | right   | N/A                                    | [requisition_line]suggested_quantity     | This is calculated at sync time              |
| Supplied Quantity  | A          | Supply This Invoice | Yes      | - Not finalised - Positive integer - Cannot exceed the amount of available stock.                         | 0                                                                                                                                                                                                                                                                                                                                                                       | N/A                                                                                                | right   | RequisitionItem.suppliedQuantity       | [requisition_line]actualQuan             |                                              |
| Opening Stock      | B          | Opening             | Yes      | - Not Finalised - Positive Integer - Must be >=  (incoming + outgoing + adjustments)                      | Equal to the Closing Balance of the most recent requisition in the last* period                                                                                                                                                                                                                                                                                         | N/A                                                                                                | right   | **NEW** RequisitionItem.openingStock   | [requisition_line]previous_stock_on_hand | Guessing the mSupply column.                 |
| Days out of Stock  | B          | Days out of Stock   | Yes      | - Not Finalised - Positive Integer - 0 >= DoS <= number of days withing period.endDate - period.startDate | 0                                                                                                                                                                                                                                                                                                                                                                       | N/A                                                                                                | right   | **NEW** RequisitionItem.daysOutOfStock | [requisition_line]DOSforAMCadjustment    | Is that camel case? hehe                     |
| Receipts           | B          | Incoming            | Yes      | - Not Finalised. - Postive Integer - Must be >= opening + outgoing + adjustments                          | Sum of all TransactionBatch.totalQuantity where TransactionBatch.transaction === 'customer_invoice and TransactionBatch.transaction.otherParty === the customer for this requisition for all TransactionBatch where TransactionBatch.transaction.confirmDate >= requisition.period.startDate and TransactionBatch.transaction.confirmDate <= requisition.period.endDate | N/A                                                                                                | right   | **NEW** RequisitionItem.outgoing       | [requisition_line]Cust_stock_order       | Guessing!                                    |
| Consumption        | B          | Outgoing            | Yes      | - Not Finalised. - Positive Integer. - Must be <= (opening + incoming + adjustments)                      | 0                                                                                                                                                                                                                                                                                                                                                                       | N/A                                                                                                | right   | **NEW** RequisitionItem.consumption    | [requisition_line]adjusted_consumption   | Guessing!                                    |
| Adjustments        | B          | Adjustments         | Yes      | - Not Finalised. - Positive/Negative Integer - Must be >= (opening + incoming + outgoing                  | 0                                                                                                                                                                                                                                                                                                                                                                       | N/A                                                                                                | right   | **NEW** RequisitionItem.adjustments    | [requisition_line]Cust_loss_adjust       | Guessing.                                    |
| Closing Stock      | B          | Closing             | No       | N/A                                                                                                       |                                                                                                                                                                                                                                                                                                                                                                         | open + incoming + outgoing + adjustments                                                           | right   | RequisitionItem.stockOnHand            | [requisition_line]stock_on_hand          | Duplicate of Their Stock column              |
| Requested Quantity | B          | Requested           | Yes      | - Not Finalised - Positive Integer                                                                        | 0                                                                                                                                                                                                                                                                                                                                                                       | N/A                                                                                                | right   | RequisitionItem.requiredQuantity       | [requisition_line]Cust_stock_order       |                                              |

**Comment by joshxg** [comment]
Sorry - it's all just clicking now - been doing temperatures and vvm status' for too long:

- We *will* need positive and negative adjustment columns as we can't really do negatives :(
- It is also a bit of a pain for the validation over multiple columns:

Have: 

Opening: 20
Incoming: 10
Outgoing: 30
Closing: 0

If I edit opening:
Opening: 2
Incoming: 10
Outgoing: 30
Closing: -18

Will need to 0 out opening, incoming and outgoing

**Comment by joshxg** [comment]
- We have `MONTHS_LEAD_TIME` preference, which is added to the `maxMOS` of the `orderType` to form the `daysToSupply`:

`const daysToSupply = ((monthsLeadTime || 0) + (maxMOS || 1)) * 30;`

A little unsure on behaviour here for customer requisitions.

- Threshold MOS: Does this play a role with customer requisitions? Should it be saved to the `thresholdMOS` field and we introduce a toggle, or leave it out?

**Comment by joshxg** [comment]
Another question:

- Are we needing to implement Indicators?

**Comment by andreievg** [comment]
> Was wondering if we need a way to distinguish between Requisitions entered vs received via sync

> We don't for any other page. I think it's a good idea but a little out of scope for this feature?

The only reason was to make sure program requisitions that are coming from other stores, can't be edited (apart from the usual supply quantity). We did something like this originally fort supplier invoices (when they come through sync can't delete lines), not sure if it's there still.

> Threshold MOS: Does this play a role with customer requisitions? Should it be saved to the thresholdMOS field and we introduce a toggle, or leave it out?

I think leave it out for now, not part of JSI requirements, but does introduce some inconsistency in how we do it in mobile/desktop and supplier/customer, maybe we can just make an issue to flag it as something to look at later. Same with months lead time.

Will look at the spreadsheet soonish

**Comment by andreievg** [comment]
As per telegram chat:

**Validation**

Auto validation would be hard to get right, so maybe allow negative closing stock, but have an indication on the row that it's wrong and don't allow finalisation (maybe in finalisation error modal can show more info about rows/formula).

`Indication on the row`
 * Visible even when column set is switched
* Ideally cells that affect the validation will have indications
* Ideally main cell (closing stock) will have more of an indication then the ones that affect the validation

**Comment by andreievg** [comment]
> Are we needing to implement Indicators?

Regimen data ? Nope

**Comment by joshxg** [comment]
Have played around this as an implementation - will also validate when trying to finalize. All good?

![validation](https://user-images.githubusercontent.com/35858975/93954189-2923de80-fda1-11ea-9a0f-f6f517e931e9.gif)

**Comment by joshxg** [comment]
Also: looking for better names for columns/data entry!

**Comment by andreievg** [comment]
very cool!
