### ISSUE TITLE
v7.0.0 Release Discussion

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3262]
## RELEASE VERSION

v7.0.0

### SUMMARY

This release will be primarily focussed on the new vaccine module.

The development deadline is 15th January

### Chores
- [x] #3258 Dependency upgrades for React Native 0.63.3

### Refactors/Enhancements
- [x] Unable to spread realm objects: https://github.com/openmsupply/mobile/issues/3528
- [x] Bugsnag will now record previous actions that had been dispatched https://github.com/openmsupply/mobile/issues/3267

### Features
- [x] #3161 - Vaccines Module

### Bugs
- [x] Creating automatic order creates zero quantity lines: #3738.
- [x] Regexp used in MultiSelectList can cause a crash: #3537.
- [x] Current stock shows batches out of order: #3533.
- [x] When unselecting a master list in `MultiSelectList` the font is invisible: #3530.
- [x] Inactive insurance policies were applying the discount amount: https://github.com/openmsupply/mobile/issues/3565
- [x] Incorrect string when deleting supplier requisitions: https://github.com/openmsupply/mobile/issues/3207
- [x] Prescription quantity input now defaults to the numeric keyboard: https://github.com/openmsupply/mobile/issues/3327

## Documentation

- Vaccine Module
- [x] Draft https://docs.google.com/document/d/1MD17DWP5BJYVh7KuHsdexHUhSMBB0JWg8TeBAR4_gBY/edit
- [x] Published

**Comment by joshxg** [comment]
Going to be a bit of a rush to get this release done over the holiday period for the middle of January!

Getting started on the vaccine module now, please comment if there are any other bug/features/refactors that you think should be done in this release!

🎉

**Comment by joshxg** [comment]
UPDATE:

- Still developing Vaccines
- We are behind as of 17th january. Need aim is for the start of february.

**Comment by joshxg** [comment]
Update:

- The vaccines module is now entering the testing phase which should be 1-2 weeks.
- New documentation will be updated during this time

Looking at a release toward the end of February

**Comment by joshxg** [comment]
👋 

We've just released RC3 here: https://github.com/openmsupply/mobile/releases/tag/v7.0.0-rc3

This has a fair amount of bug fixes found from RC2 - so, thanks for testing!

Still in early stages of testing so plenty more bugs to find 🐛

**Comment by joshxg** [comment]
👋 

RC4 is here: https://github.com/openmsupply/mobile/releases/tag/v7.0.0-rc4

Even more bug fixes. Getting closer, but the branch is still relatively unstable with various bugs coming up. Not stable enough to start narrowing down specific issues to be fixed before we can release. So, a fair amount more testing needs to be done, I think!

**Comment by joshxg** [comment]
👋 

RC6 is here: https://github.com/openmsupply/mobile/releases/tag/v7.0.0-rc6

Fixed quite a lot of bugs since RC4 and we're starting to get to a very stable point. I think there 

Waiting on bugs:
- #3546 
- #3587 

But more testing is always loved ❤️

**Comment by joshxg** [comment]
👋 

Have released RC7 today also : https://github.com/openmsupply/mobile/releases/tag/v7.0.0-rc7

This has the above bug fixes for:
- #3546 
- #3587 

Known bugs to be fixed include:
- #3514 

Other than that, we're just waiting to hear from testers regarding the stability for this release!

**Comment by joshxg** [comment]
Sorry for the lack of updates!

I've had to step away from the release to get on top of other important features leaving @katherine-sussol and @wlthomson to handle this release from here!

**Comment by wlthomson** [comment]
RC8 released today: https://github.com/openmsupply/mobile/releases/tag/v7.0.0-rc8

Fixes:

- https://github.com/openmsupply/mobile/issues/3623
- https://github.com/openmsupply/mobile/issues/3627
- https://github.com/openmsupply/mobile/issues/3628

**Comment by wlthomson** [comment]
Looks like we are getting to a point of stability, but a bit more testing is required before releasing! 

Assuming adequate coverage (i.e. another round of the [vaccines template](https://github.com/openmsupply/mobile/issues/2913)) and absence of any big bugs found in this round of testing, I think `rc9` will be suitable as a final release candidate.

@katherine-sussol @ArpitaSussol Thoughts?

**Comment by ArpitaSussol** [comment]
> Looks like we are getting to a point of stability, but a bit more testing is required before releasing!
> 
> Assuming adequate coverage (i.e. another round of the [vaccines template](https://github.com/openmsupply/mobile/issues/2913)) and absence of any big bugs found in this round of testing, I think `rc9` will be suitable as a final release candidate.
> 
> @katherine-sussol @ArpitaSussol Thoughts?

I am not super sure about Breach column included in Customer Invoice and Replacing sensor button section as for Breach  to be shown for an item, an item should be placed in contact with sensor which seems not possible physically from testing side . Regarding replacing sensor button, don't have two sensor right now.

Also can you have look into this issue https://github.com/openmsupply/mobile/issues/3664? is this blocker or not ?

Beside that, i don't think there is any blocking issue to be seen. So good to go and build rc9 :)

**Comment by katherine-sussol** [comment]
Yes, I also think it's looking pretty stable now.

I'll give the sensor replacement a more thorough test today with mocks to have that area covered.
I think also maybe we should look at https://github.com/openmsupply/mobile/issues/3514 that one sounds a little worrying 🤔. Aside from these two once (and merge of https://github.com/openmsupply/mobile/pull/3654) should be good to go?

**Comment by joshxg** [comment]
👋

@ArpitaSussol has smashed through the templates last night and got most of them done. Just a few left to cover (in the needs build testing column)

Few bugs found which are milestoned 7.0:

https://github.com/openmsupply/mobile/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+milestone%3A7.0.0

**Comment by joshxg** [comment]
Nice work everyone this has been released here: https://github.com/openmsupply/mobile/releases/tag/v7.0.0
