### ISSUE TITLE
Bluetooth thunks

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3319]
## Is your feature request related to a problem? Please describe.

Require thunks to accomplish the following tasks

- [x] #3355 Download temperatures from a single and multiple sensors
- [x] #3351 Scan for new sensors
- [x] #3352 Send a command to blink a sensor
- [x] #3354 Send a command to change the log interval of a sensor

## Describe the solution you'd like

Thunks similar to `temperatureSyncActions` but using `BleService` and `TemperatureLogManager`/`BreachManager`.

## Implementation

Possibly best to use a singleton `BleService` and manager classes? Otherwise can use `extraArgument` inside the thunk middleware.

## Describe alternatives you've considered

N/A

## Additional context

N/A
