### ISSUE TITLE
State management for downloading temperature logs

### ISSUE THREAD

**Issue by katherine-sussol** [openmsupply/mobile#3380]
## Is your feature request related to a problem? Please describe.

- Need some state management for downloading temperature logs, some current thoughts:
  - When was the last sync?
    - This is in the Marvel designs (see below)
  - Was the last sync attempt successful?
    - So we can possibly add an indication to the UI somehow? E.g. change the sensor color or icon
  - Is a download in progress? 
    - Could make the last sync time arrow spin? 😆 

## Describe the solution you'd like

TBD

## Implementation

Split into separate issues
- [x] #3406:  Extract and update bluetooth sensor 'Download' Actions/Reducers
- [x] #3405: Extract bluetooth sensor 'Scan' Actions/Reducers
- [x] #3404: Extract bluetooth sensor 'Update' Actions/Reducers 
- [x] #3402: Extract bluetooth sensor 'Blink' Actions/Reducers

## Describe alternatives you've considered

Not storing state, but there are some elements in the UI that will require it, e.g. Sensors Page
![image](https://user-images.githubusercontent.com/65875762/105651176-f2aacb80-5f1a-11eb-8435-25f3085fcfa3.png)

**Comment by joshxg** [comment]
> Could make the last sync time arrow spin?

I think this is cool!!


### When was the last sync?
- Need to know which sensor/location, so possibly a lookup table
- So need to put something like this somewhere?
```
{
    lastSync: {
		[macAddress]: date
        ...
    }
}
```

### Was the last sync attempt successful
- Similar to above, just we can have some codes which mean 'something'?


### Is a download in progress
- Similar again? Lookup of mac: [bool]?

Personally I like the idea of having a reducer and actions for possibly, each of these concerns..

Using `combineReducers` you can do something for example:

```
const LastDownloadDateReducer = () => ...
const LastDownloadStateReducer = () => ...
const LastDownloadReducer = combineReducers({lastDownloadDate: LastDownloadDateReducer, lastDownloadState: ...})
```

and then can even:

```
const BlinkReducer = () => ...
const LastDownloadReducer = () => ...
const VaccineReducer = combineReducers({lastDownload: lastDownloadReducer, blink: ...)
```

Which creates the shape:

```
{
    vaccine: {
		lastDownload: {
			lastDownloadDate: {
				[macAddress1]: date,
				[macAddress2]: date,
				...
			},
			lastdownloadState: {
				[macAddress1]: [state],
				[macAddress2]: [state],
				...
			}
   		},
		blink: { 
			...
		}
    }
}
```

Which is quite nested (but the combining of reducers doesn't really create the nesting, it'd sort of happen anyway?) but means that a reducer, for example `LastDownloadStateReducer` is only passed it's own slice of state, and working with that data and creating state updates is easier than having to do immutable updates to a heavily nested piece of state.

**Comment by joshxg** [comment]
Just putting down the current redux state for vaccines cause I had it on my other screen thinking about it anyway..

vaccine (currently bluetooth related infos):
```
{
  isScanning: false,
  scannedSensorAddresses: [],
  setLogIntervalFor: '',
  sendingBlinkTo: '',
}
```

newSensor (used in the new sensor flow):
```
{
macAddress: '',
code: '',
name: '',
loggingDelay: moment(new Date()).add(5, 'minutes').toDate(),
logInterval: 300,
HOT_CUMULATIVE: { duration: 300, temperature: 8 },
COLD_CUMULATIVE: { duration: 300, temperature: 2 },
HOT_CONSECUTIVE: { duration: 300, temperature: 8 },
COLD_CONSECUTIVE: { duration: 300, temperature: 2 },
}
```

sensorDetail (used when clicking the settings cog and navigating to edit a sensor/location):
```
{
name: sensor?.name ?? '',
code: sensor?.location?.code ?? '',
macAddress: sensor?.macAddress ?? '',
logInterval: sensor?.logInterval ?? 0,
HOT_CUMULATIVE: { duration: 0, threshold: 99, temperature: 2 },
HOT_CONSECUTIVE: { duration: 0, threshold: 99, temperature: 2 },
COLD_CUMULATIVE: { duration: 0, threshold: 99, temperature: 2 },
COLD_CONSECUTIVE: { duration: 0, threshold: 99, temperature: 2 },
batteryLevel: sensor?.batteryLevel ?? 0,
lastSyncDate: sensor?.lastSyncDate ?? new Date(),
}
```

fridge (used on the fridge detail page, probably in the vaccine module page):
```
{
fridges: locationsWithASensor,
selectedFridge: locationsWithASensor[0],
fromDate: moment(new Date()).subtract(30, 'd').startOf('day').toDate(),
toDate: moment(new Date()).endOf('day').toDate(),
}
```

**Comment by katherine-sussol** [comment]
I think a lookup table for each sensor with mac address and last sync/download status sounds good. I'll take a go at this using separate actions/reducers (maybe under a Bluetooth subfolder under each of actions/reducers?) 

With one for each of
- Blink
- Download
- Scan
- LogInterval
- ButtonDisable 

As part of this I also really want to rename these to not have vaccine in the name, the naming is making less sense as we go 🤣 ). Think it makes sense to split this out into two issues, one for the restructure and one for the new states?

**Comment by joshxg** [comment]
@katherine-sussol  sounds good to me.

Maybe @Chris-Petty / @mark-prins  have some thoughts?

- I'm not sure, but maybe `logInterval` and  `buttonDisable` might be better off consolidated as `updating` or something like that as these are both sort of a process of updating the physical sensor?
- I'd even maybe split it into an issue per concept/slice?

**Comment by mark-prins** [comment]
it all sounds good! +1 for spinning the icon when downloading 😄 
Agree also about combining the `logInterval` and `buttonDisable` 
I also like the intention to rename vaccine to bluetooth and make things more generic. this is all about temperature monitoring - vaccines are a specific use-case and not the primary function, and I think the name is better when relating to the high level function.

**Comment by joshxg** [comment]
@katherine-sussol this ones all done now right? or am I silly?

**Comment by katherine-sussol** [comment]
Oh! Yes all done - have forgotten to close
