### ISSUE TITLE
v8.0.0 Release discussion

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3597]
## RELEASE VERSION

v8.0.0

### SUMMARY

This release is aimed at building features to aid Tonga with their COVID-19 vaccine roll-out.

~~The development deadline is 12th March~~
The development deadline is 26th March

### Features
- [x] #3595 Patient Events
- [x] #3592 Vaccine dispensing
- [x] #3594 Additional patient details
- [x] https://github.com/openmsupply/mobile/issues/3795 Adverse drug effects
- [x] #3842 Customisable interval for inactivity log out
- [x] #3821 Customisable sync interval

### Bugs

- [x] https://github.com/openmsupply/mobile/issues/3740 - Customer credits table has dissapeared!
- [x] #3898  After finalising a customer requisition the whole page wasn't disabled correctly
- [x] #3897 After initialising a mobile store when there are modules installed, the menu page wasn't showing the modules 
- [x] #3890 Sometimes records deleted on the server weren't deleted on mobile

## Documentation

- Vaccine dispensing
    - [x] Draft : https://docs.google.com/document/d/1_BF7HOtc_T_En9TmLlX7L_ce2KT-fhcU61PD_k7tk0Y/edit
    - [x] Published : https://docs.msupply.foundation/en:mobile:user_guide:vaccine_dispensing
- Adverse drug reactions
	- [x] draft: https://docs.google.com/document/d/1_BF7HOtc_T_En9TmLlX7L_ce2KT-fhcU61PD_k7tk0Y/edit
	- [X] published: https://docs.msupply.foundation/en:mobile:user_guide:adverse_drug_reactions

**Comment by joshxg** [comment]
The deadline for this release was previously the 12th of March.

Tongas deployment have been delayed, we are therefore taking a bit more time for this release.

I've updated the deadline to the 26th

**Comment by joshxg** [comment]
We're looking OK for the deadline of the 26th.

Great testing by @ArpitaSussol and @nishaSussol thanks so much!!

A few bugs found and are in the process of being fixed+re-tested.

We also have the last feature to be added: adverse drug reactions which should be complete and enter testing within the next day or two!

**Comment by joshxg** [comment]
`8.0.0` has been released :)

Didn't quite make the deadline but thanks everyone who contributed! We hope Tonga's vaccine rollout is a great success!
