### ISSUE TITLE
Tonga deployment admin tasks

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3600]
This is an issue to track and consolidate tasks which need to be accomplished before deploying mSupply mobile into Tonga

### Resources

- Google drive for this project: https://drive.google.com/drive/u/2/folders/15K_jeqz2XN2NeguD48r3najASU360oP6

### Prerequisites

- [x] Exact list of patient data survey fields, with default values and data types
- [ ] Exact list of patient adverse effect fields, with default values and data types
- [x] Exact list of occupations a user can select
- [x] Exact list of ethnicities a user can select
- [x] Exact list of religions a user can select [Is this nationality???]

### Tasks

- [x] Create a data schema for patient data survey fields and ensure this is in the Tonga data file
- [ ] Create a ui schema for patient data survey fields and ensure this is in the Tonga data file
- [ ] Create a data schema for patient adverse effects and ensure this is in the Tonga data file
- [x] Create a ui schema for patient adverse effects and ensure this is in the Tonga data file
- [x] Ensure all occupations are in the Tongan data file
- [x] Ensure all ethnicities are in the Tongan data file
- [x] Ensure all nationalities are in the Tongan data file
- [x] Ensure all patients are synced to all tablets (Are we doing this into an mSupply version or using footrunner? Do we need all related patient data?)
- [x] Ensure the Tonga data file has inventory adjustment reasons for open vial wastage
- [x] Ensure the Tonga data file has VVM status’ (? - unsure if needed)

**Comment by joshxg** [comment]
Have made an mSupply issue which will be able to handle this: https://github.com/sussol/msupply/pull/8196
