### ISSUE TITLE
Vaccine dispensing system tasks

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3601]
## Is your feature request related to a problem? Please describe.

There are some system/desktop related tasks which need to be completed for this project. This issue will track these tasks.

## Tasks

- [x] Version update code to re-send some system data [Ensuring system data is sent to a mobile store. This might not be needed for Tonga but we could potentially forget in the future. If some records are created i.e. `[Occupation]` before mobile is upgraded to 8.0, mobile may potentially reject the record and never be resent it.] in `upgradeMobileSite` method
- [x] Add form config table [TBD- potentially interface to insert/view configs in a later version]
- [x] Add sync triggers to: 
	- [x] `[Occupation]` as system data.
	- [x]  `[Ethnicity]` as system data.
	- [x]  `[Nationality]` as system data.
- [x] Alter sync for `name_note` and `name`:
	- [x] Make `name_note` sync to every store like system data (don't prevent edits?)
	- [x] Make `name` updates
		- [x] Remove the line (L118) in `sync_process_sync_record` which prevents updates from non-home stores
		- [x] Update patient lookup API to make `name_store_join` records for `names` looked up
		- [x] Ensure that if a patient is edited on a satellite, each satellite that has that record visible is updated also
- [x] Add an object field to the `name_note` table

**Comment by joshxg** [comment]
@mark-prins if you have an opinion before I go making some desktop issues ❓

### Config schema

![image](https://user-images.githubusercontent.com/35858975/109124316-a8ce3300-77af-11eb-8d7d-703b869dc9ef.png)

### name_note
- Add field: `data`: `object`?

### System data
- Should we add a `Religion` table?

### `name` updates
- Should we disable the line preventing updates according to some pref? (and what kind of pref... 🙄 )  customisation code? (probably the fastest but hackiest)
