### ISSUE TITLE
Vaccine Dispensing Epic

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3615]
## Feature summary

A client requires a way to record additional information against patients while dispensing individual doses to a patient.

So, we need to provide a way to render dynamically created forms from some config as well as providing a way for users to issue single doses.

### Multi-dose dispensing

We will make a new page which will be a wizard, similar to our regular dispensing page which is designed specifically for issuing vaccines.

This page will allow a user to:
- **Step 1:** Select a patient either from local storage or online
- **Step 2:** Update any patient details as well as fill or update a dynamically created survey form
- **Step 3:** Select a vaccine + number of doses

In the end, the result will be a patients details are updated and a prescription issued.

#### Patient Data / Patient Survey data

We have the majority of patient details covered, but a few more are required which will be added to the name record.
- Occupation
- Ethnicity
- Nationality
- Village
- District

However there are additional fields which are quite covid/vaccine specific and as such won't be saved against the name record, instead will be saved as a name_note and related to the patient

To generate forms, we will create a [JSON schema](https://json-schema.org/) to represent the form, which will be created as system data and sent to satellite sites which will render a form based on that config.

### Adverse drug reactions

TBD

## Resources

- Google drive: https://drive.google.com/drive/u/2/folders/15K_jeqz2XN2NeguD48r3najASU360oP6
- Requirements: https://docs.google.com/spreadsheets/u/2/d/1c2qTyC4xPPOLgKc2V5ptpaI2A8C-TfDisufqseAXXFk/edit?usp=drive_web&ouid=106487477937636726671
- Design brainstorming: https://drive.google.com/drive/u/2/folders/15K_jeqz2XN2NeguD48r3najASU360oP6
- Patient survey example spreadsheet: https://docs.google.com/spreadsheets/d/1eYqarZ9KDnK8F6k0Yx0HwuRYt-1SajSd/edit#gid=931076148
- Patient survey data breakdown: https://docs.google.com/spreadsheets/u/2/d/1DGSWaN-fPf0aMcX_V5ZiVtngnktM3aeK-Ds7tyTKxAo/edit?usp=drive_web&ouid=106487477937636726671
- JSON Schemas: https://json-schema.org/
- Feature branch : https://github.com/openmsupply/mobile/tree/%23feature/vaccine-dispensing

## Tasks

Each set of tasks are broken down into sections, however each section may have overlapping concerns with others as they are related to the same feature.

### Admin tasks before deployment
- [ ] https://github.com/openmsupply/mobile/issues/3600

### System/Desktop
- [ ] https://github.com/openmsupply/mobile/issues/3601
	- [x] Version update code -  https://github.com/sussol/msupply/issues/8124 
	- [x] Add form config table - https://github.com/sussol/msupply/issues/8123
	- [x] Sync triggers for Ethnicity/occupation/nationality tables - https://github.com/sussol/msupply/issues/8125
	- [x] Alter sync for name_note - https://github.com/sussol/msupply/issues/8127
	- [x] Alter sync for name - https://github.com/sussol/msupply/issues/8126
	- [x] Alter name_note table - https://github.com/sussol/msupply/issues/8200

### Multi-dose dispensing
- https://github.com/openmsupply/mobile/issues/3592
 	- [x] Adding redux state for vaccine dispensing page https://github.com/openmsupply/mobile/issues/3617
	- [x] Add createRecord case for saving vaccine prescriptions https://github.com/openmsupply/mobile/issues/3616
	- [x] Regression testing and fixing side effects https://github.com/openmsupply/mobile/issues/3618
	- [x] Add vaccine dispensing page https://github.com/openmsupply/mobile/issues/3606
	- [x] Add vaccine dispensing step one https://github.com/openmsupply/mobile/issues/3607
	- [x] Add vaccine dispensing step two https://github.com/openmsupply/mobile/issues/3608
	- [x] Add vaccine dispensing step three https://github.com/openmsupply/mobile/issues/3609

### Additional patient details
- https://github.com/openmsupply/mobile/issues/3594
	- [x] Adding fields to the schema https://github.com/openmsupply/mobile/issues/3614
	- [x] Adding fields to the UI https://github.com/openmsupply/mobile/issues/3619

### Patient surveys
- [x] #3595 
	- [x] Add patient events and name notes to the schema #3620
	- [x] createRecord case for name_note #3621
	- [x] Add a package to generate JSON schema forms https://github.com/openmsupply/mobile/issues/3611
	- [x] Add widgets for JSON schema forms https://github.com/openmsupply/mobile/issues/3612
	- [x] Add patient surveys to the patient edit modal #3613
