### ISSUE TITLE
v8.1.0 Release Discussion

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#3904]
## RELEASE VERSION

v8.1.0

### SUMMARY

The current goal for this release is to get QR scanning in for patient dispensing (for Vanuatu), along with a selection of small bug fixes and enhancements.

The deadline is TBD.

### Chores
- [x] #3922 - 8.1 dependency upgrades
- [x] #3542 - Picker is being deprecated out of react-native core

### Refactors/Enhancements
- [x] #4022 - Patient history lookup - for all patients
- [x] #4139 - Improve date picker in Mobile ColdChain module
- [x] #4142 - Notification badge for (in-progress) Cold Chain breaches

### Features
- [x] #4066 - QR Code patient scanning

### Bugs
- [x] #426 - Incorrect version number on install/update
- [x] #2746 - Items currently being added to a prescription show on patient history
- [x] #2795 - Confirm button is misleading in supplier credits for items with 0 stock
- [x] #3279 - Badges do not update until you navigate into the window
- [x] #3736 - Monthly usage is too high for newly added items
- [x] #3747 - Temperature log export with no logs causes indefinite load spinner animation
- [x] #3757 - When temperatures of logs cross both breach boundaries, no breach is created
- [x] #3770 - Prescriber: Adding/Updating Prescriber's Gender field is not reflecting/saving
- [x] #3787 - Removing sensor with logs for few days is keep showing detail page
- [x] #3925 - Requisition created date is non-nullable on mobile but not desktop 
- [x] #4126 - Warning on Cash Register screen
- [x] #4133 - Prescriber: Adding/Updating Prescriber's Address/Address 2 field is not reflecting/saving
- [x] #4138 - Patient lookup results in wrong address

## Documentation

- TBD
