### ISSUE TITLE
QR Code patient scanning

### ISSUE THREAD

**Issue by joshxg** [openmsupply/mobile#4066]
## Is your feature request related to a problem? Please describe.

We don't have a way to scan QR codes for a patient to look them up in the system.

## Describe the solution you'd like

When dispensing a vaccine through the `Vaccination` page, a user should be able to use the camera of a tablet to scan a patients physical card which has a QR code on it to find the patient within the system.

## Implementation

- [x] #4068: Add a field: `[name]barcode` to the realm schema. This already exists in mSupply.
- [x] #4070:  Add a button in the `Vaccination` page - `"Scan QR Code"` which will open a modal with a QR code scanning component
- [x] #4071: Use the QR code string to query on the `[name]barcode` field
- [x] #4072:  If there is no result, try and use the online patient search to find the patient
- If a search returns a result, take the user to Step 2 of the vaccine dispensing flow with found details prepopulated. If there is no result, let the user know there is no patient which matches [Future issue: create the patient?]
- [ ] #4073 [UNCONFIRMED]: Add the ability to manually search by patient code/national ID (unsure if `code == nationalID`)

## Describe alternatives you've considered

🤷 

## Additional context

- Can assume the string returned from the QR code is exactly what is saved to the barcode field. We need to get a tester from Vannuatu to make sure of this, but parsing and getting the real ID of the patient shouldn't be too bad.
- Going to try and get the tablet they're using to ensure that the camera scanning is OK
- Can probably break this down into quite a few issues

**Comment by katherine-sussol** [comment]
Closing as the feature is more or less implemented, change requests can be made via separate issues 😺

**Comment by katherine-sussol** [comment]
Added screenshot and some notes to vaccine dispensing docs: https://docs.msupply.foundation/en:mobile:user_guide:vaccine_dispensing#step_onepatient_details
