### ISSUE TITLE
Requisition regimen data collection

### ISSUE THREAD

**Issue by Chris-Petty** [openmsupply/mobile#883]
### Description:
When entering a program requisition, the user needs to be able to enter regimen data into the requisition similar to desktop implementation for central reporting purposes.

### Tasks
- [x] In a requisition for a program there is a button to view regimen data
- [x] Program requisitions are made with customData including regimen questions
- [x] The regimen data is presented in a page or modal (former might be better if we ever refactor regimen data collection into a more distinct feature), table or other
- [x] Regimen questions are from program master list custom data
- [ ] Can't finalise if any questions are `isRequired`
- [ ] Un-editable when requisition finalised
- [x] Syncs to desktop

**Comment by Chris-Petty** [comment]
Fixed in #941

**Comment by joshxg** [comment]
# Testing
- [x] Can view/edit requisition regimen data in a supplier requisition
- [x] Syncs to desktop correctly
- [x] Syncs from desktop correctly

*Tested all sorts of things, like not having required and making sure it can still be opened, funny data types, making sure it can still be opened in msupply if regimen which are required weren't filled out but still finalised etc, seems good*
